"""FusionSpace terminal styles for Python command-line tools. No dependencies.
Generated by tools/build/kit_product.py in the fusionspace-design repository; edit there, not here. See product/cli.md.

    from fs_style import S, paint, use_color
    color = use_color(sys.stderr, flag=args.color)          # "auto" | "always" | "never"
    print(paint("warning:", S.WARNING, color), "the main opens late", file=sys.stderr)
"""
import os, sys

class S:
    """ANSI roles: the user's terminal theme decides the actual colours."""
    HEADING = "\x1b[1m"   # section titles, table headers, the first line of a result
    LITERAL = "\x1b[1;34m"   # commands, flags and values to type
    PLACEHOLDER = "\x1b[34m"   # <FILE>, <MOTOR> in help
    OK = "\x1b[32m"   # CONT, passed, fired
    CAUTION = "\x1b[33m"   # values near a limit
    WARNING = "\x1b[1;33m"   # warning:
    DANGER = "\x1b[1;31m"   # error:, NO CONT, failed checks
    PREDICTED = "\x1b[35m"   # simulated or forecast values beside measured ones
    MUTED = "\x1b[2m"   # separators and decoration only
    ERROR = DANGER
    HELP = LITERAL
    NOTE = HEADING
    RESET = "\x1b[0m"

def use_color(stream=sys.stdout, flag="auto"):
    """The flag, then NO_COLOR, then FORCE_COLOR / CLICOLOR_FORCE, then: a terminal, and TERM isn't dumb."""
    if flag in ("always", "never"):
        return flag == "always"
    if os.environ.get("NO_COLOR"):
        return False
    if os.environ.get("FORCE_COLOR") or os.environ.get("CLICOLOR_FORCE", "0") not in ("", "0"):
        return True
    return hasattr(stream, "isatty") and stream.isatty() and os.environ.get("TERM") != "dumb"

def paint(text, style, color=True):
    return f"{style}{text}{S.RESET}" if color else text

def truecolor():
    """True when the brand banner may use 24-bit colour."""
    return os.environ.get("COLORTERM") in ("truecolor", "24bit")
