// SPDX-License-Identifier: Apache-2.0 · Copyright 2026 Neer Patel
// FusionSpace content-layer parts for SwiftUI. Generated by tools/build/kit_mobile.py from source/product/mobile/; edit there.
// Needs FusionSpaceColors.swift (product/tokens/) and the fonts in the app bundle. iOS 17+, macOS 14+.
//
// These are the parts FusionSpace owns (product/mobile.md): readouts, status chips, sheet headers, the title block, the held
// confirmation for arming, and commanded-vs-confirmed state. Bars, lists, switches and pickers stay the system's.
import SwiftUI
#if canImport(UIKit)
import UIKit
#endif

// MARK: - Signals

/// A state with a word and a shape. Color is the third cue, never the only one (product/foundations.md).
public enum FSSignal: Sendable {
    case danger, caution, ok, info, off, stale, predicted

    /// The SF Symbol drawn when no FusionSpace custom symbol is given. The domain icons in product/icons/ replace these as
    /// custom symbols (drawn on the SF Symbols template from the 24 px masters).
    public var defaultSymbol: String {
        switch self {
        case .danger, .caution: return "exclamationmark.triangle"
        case .ok: return "checkmark.circle"
        case .info: return "info.circle"
        case .off: return "minus"
        case .stale: return "clock"
        case .predicted: return "chart.line.uptrend.xyaxis"
        }
    }
}

/// A status chip: `CONT`, `ARMED`, `NOT USED`. Danger, caution and normal are filled the same on every background, like a
/// safety sign; the others are outlined.
public struct FSStatus: View {
    let signal: FSSignal
    let word: String
    let detail: String?
    let symbol: String?
    let minHeight: CGFloat

    /// - Parameters:
    ///   - word: the state, shown in capitals (`CONT`, `ARMED`).
    ///   - detail: a value after it, shown as written so units keep their case (`Link · 0.3 s`, not `0.3 S`).
    ///   - minHeight: 24 pt by default; 20 on a watch.
    public init(_ word: String, signal: FSSignal, detail: String? = nil, symbol: String? = nil, minHeight: CGFloat = 24) {
        self.word = word; self.signal = signal; self.detail = detail; self.symbol = symbol; self.minHeight = minHeight
    }

    public var body: some View {
        FSPaletteReader { p in
            HStack(spacing: 6) {
                Image(systemName: symbol ?? signal.defaultSymbol).imageScale(.small)
                HStack(spacing: 0) {
                    Text(word.uppercased())
                    if let detail { Text(" · \(detail)") }
                }
                .font(FS.label().weight(.semibold))
            }
            .lineLimit(1)
            .padding(.horizontal, 8)
            .frame(minHeight: minHeight)
            .foregroundStyle(foreground(p))
            .background(fill(p))
            .overlay(border(p))
            .accessibilityElement(children: .ignore)
            .accessibilityLabel(Text(detail.map { "\(word), \($0)" } ?? word))
        }
    }

    private func foreground(_ p: FSPalette) -> Color {
        switch signal {
        case .danger: return FS.onDangerFill
        case .caution: return FS.onCautionFill
        case .ok: return FS.onOkFill
        case .info: return p.action
        case .off, .stale: return p.inkMuted
        case .predicted: return p.predicted
        }
    }
    @ViewBuilder private func fill(_ p: FSPalette) -> some View {
        switch signal {
        case .danger: FS.dangerFill
        case .caution: FS.cautionFill
        case .ok: FS.okFill
        case .stale: FSHatch(color: p.inkFaint).background(p.surface)
        default: Color.clear
        }
    }
    @ViewBuilder private func border(_ p: FSPalette) -> some View {
        switch signal {
        case .info: Rectangle().strokeBorder(p.action, lineWidth: 1)
        case .off, .stale: Rectangle().strokeBorder(p.ruleStrong, lineWidth: 1)
        case .predicted: Rectangle().strokeBorder(p.predicted, style: StrokeStyle(lineWidth: 1, dash: [4, 2]))
        default: EmptyView()
        }
    }
}

/// 45° hatching, 1 pt lines every 6 pt: unavailable, stale or out of range (an ISO 128 section line).
public struct FSHatch: View {
    var color: Color
    public init(color: Color) { self.color = color }
    public var body: some View {
        Canvas { ctx, size in
            var path = Path()
            var x = -size.height
            while x < size.width {
                path.move(to: CGPoint(x: x, y: size.height)); path.addLine(to: CGPoint(x: x + size.height, y: 0)); x += 6
            }
            ctx.stroke(path, with: .color(color), lineWidth: 1)
        }
        .accessibilityHidden(true)
    }
}

// MARK: - Readouts

/// A number someone came for: a label, the value with its unit, and a qualifier that says where it came from or how far to
/// trust it. Predicted values carry a dashed underline; stale ones turn muted with a hatched block (product/data.md).
public struct FSReadout: View {
    public enum Kind: Sendable { case measured, predicted, stale }
    let label: String, value: String, unit: String, qualifier: String?
    let kind: Kind, size: CGFloat, spokenUnit: String?

    /// - Parameter spokenUnit: the unit as VoiceOver should say it ("feet above ground level" for "ft AGL").
    public init(_ label: String, value: String, unit: String, qualifier: String? = nil, kind: Kind = .measured,
                size: CGFloat = 28, spokenUnit: String? = nil) {
        self.label = label; self.value = value; self.unit = unit; self.qualifier = qualifier
        self.kind = kind; self.size = size; self.spokenUnit = spokenUnit
    }

    public var body: some View {
        FSPaletteReader { p in
            VStack(alignment: .leading, spacing: 4) {
                Text(label.uppercased()).font(FS.label()).tracking(0.7).foregroundStyle(p.inkMuted)
                HStack(alignment: .firstTextBaseline, spacing: 6) {
                    if kind == .stale {
                        FSHatch(color: p.inkFaint).frame(width: 10).overlay(Rectangle().strokeBorder(p.ruleStrong, lineWidth: 1))
                    }
                    Text(value)
                        .font(FS.readout(size))
                        .underline(kind == .predicted, pattern: .dash, color: p.predicted)
                        .foregroundStyle(kind == .stale ? p.inkMuted : p.ink)
                    Text(unit).font(FS.label()).foregroundStyle(p.inkMuted)
                }
                .fixedSize(horizontal: false, vertical: true)
                if let qualifier { Text(qualifier).font(.custom("Archivo-Regular", size: 14, relativeTo: .footnote)).foregroundStyle(p.inkMuted) }
            }
            .accessibilityElement(children: .ignore)
            .accessibilityLabel(Text(label))
            .accessibilityValue(Text(spoken))
        }
    }

    private var spoken: String {
        var s = "\(value) \(spokenUnit ?? unit)"
        if kind == .predicted { s = "predicted, " + s }
        if kind == .stale { s += ", stale" }
        if let qualifier { s += ", \(qualifier)" }
        return s
    }
}

// MARK: - Sheets and the title block

/// The top of a section: a 2 pt rule (the sheet's edge), its name, and `SHEET n / N`.
public struct FSSheetHeader: View {
    let name: String, number: Int, total: Int
    public init(_ name: String, number: Int, of total: Int) { self.name = name; self.number = number; self.total = total }
    public var body: some View {
        FSPaletteReader { p in
            VStack(spacing: 8) {
                Rectangle().fill(p.ink).frame(height: 2)
                HStack(alignment: .firstTextBaseline) {
                    Text(name.uppercased()).font(FS.heading()).tracking(0.6).accessibilityAddTraits(.isHeader)
                    Spacer()
                    Text("SHEET \(number) / \(total)").font(FS.label()).tracking(0.7).foregroundStyle(p.inkMuted)
                        .accessibilityLabel(Text("Sheet \(number) of \(total)"))
                }
            }
            .foregroundStyle(p.ink)
        }
    }
}

/// The About screen as a drawing's title block: owner, title, designation, revision, versions, data, licenses.
public struct FSTitleBlock: View {
    public struct Cell: Identifiable, Sendable {
        public let id = UUID(); let key: String; let value: String; let wide: Bool
        public init(_ key: String, _ value: String, wide: Bool = false) { self.key = key; self.value = value; self.wide = wide }
    }
    let cells: [Cell]
    let mark: Image?
    public init(_ cells: [Cell], mark: Image? = nil) { self.cells = cells; self.mark = mark }

    public var body: some View {
        FSPaletteReader { p in
            Grid(horizontalSpacing: 0, verticalSpacing: 0) {
                ForEach(rows, id: \.first!.id) { row in
                    GridRow {
                        ForEach(row) { c in
                            cell(c, p).gridCellColumns(c.wide ? 2 : 1)
                        }
                    }
                }
            }
            .background(p.surface)
            .overlay(Rectangle().strokeBorder(p.ink, lineWidth: 2))
        }
    }

    /// Two cells to a row; a wide cell takes a row to itself.
    private var rows: [[Cell]] {
        var out: [[Cell]] = [], cur: [Cell] = []
        for c in cells {
            if c.wide { if !cur.isEmpty { out.append(cur); cur = [] }; out.append([c]) }
            else { cur.append(c); if cur.count == 2 { out.append(cur); cur = [] } }
        }
        if !cur.isEmpty { out.append(cur) }
        return out
    }

    private func cell(_ c: Cell, _ p: FSPalette) -> some View {
        VStack(alignment: .leading, spacing: 2) {
            Text(c.key.uppercased()).font(FS.label()).tracking(0.9).foregroundStyle(p.inkMuted)
            HStack(spacing: 8) {
                if c.key == "Owner", let mark { mark.resizable().scaledToFit().frame(height: 18).accessibilityHidden(true) }
                Text(c.value).font(FS.readout(14, relativeTo: .body)).foregroundStyle(p.ink)
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .padding(.horizontal, 10).padding(.vertical, 6)
        .overlay(alignment: .trailing) { Rectangle().fill(p.ruleStrong).frame(width: 1) }
        .overlay(alignment: .bottom) { Rectangle().fill(p.ruleStrong).frame(height: 1) }
        .accessibilityElement(children: .combine)
    }
}

// MARK: - Commanded and confirmed

/// What the app asked the hardware to do, and what the hardware says it is, side by side. The app never assumes.
public struct FSCommandedConfirmed: View {
    let commanded: String?, confirmed: String, age: String
    public init(commanded: String?, confirmed: String, age: String) { self.commanded = commanded; self.confirmed = confirmed; self.age = age }
    public var body: some View {
        FSPaletteReader { p in
            Grid(alignment: .leading, horizontalSpacing: 12, verticalSpacing: 4) {
                GridRow {
                    Text("COMMANDED").font(FS.label()).foregroundStyle(p.inkMuted)
                    Text(commanded ?? "—").font(FS.readout(15, relativeTo: .body))
                }
                GridRow {
                    Text("CONFIRMED").font(FS.label()).foregroundStyle(p.inkMuted)
                    Text("\(confirmed) · \(age)").font(FS.readout(15, relativeTo: .body))
                }
            }
            .foregroundStyle(p.ink)
            .accessibilityElement(children: .ignore)
            .accessibilityLabel(Text("Commanded \(commanded ?? "nothing"). Confirmed \(confirmed), \(age)."))
        }
    }
}

/// The device's state as a box: SAFE outlined, ARMED inverted (product/embedded.md). Nothing else uses the inverted box.
public struct FSStateBox: View {
    let armed: Bool
    public init(armed: Bool) { self.armed = armed }
    public var body: some View {
        FSPaletteReader { p in
            Text(armed ? "ARMED" : "SAFE")
                .font(.custom("CascadiaMono-SemiBold", size: 28, relativeTo: .title))
                .padding(.horizontal, 14).padding(.vertical, 10)
                .foregroundStyle(armed ? FS.onDangerFill : p.ink)
                .background(armed ? FS.dangerFill : Color.clear)
                .overlay(Rectangle().strokeBorder(armed ? FS.dangerFill : p.ink, lineWidth: 3))
        }
    }
}

// MARK: - Held confirmation (arming)

/// Arming from the app is a second step on top of the airframe's switch: a press held for 2 s that shows the device's
/// designation (product/embedded.md). Letting go early cancels. VoiceOver and Switch Control get the accessible alternative,
/// still two steps: an action that opens a confirmation. Put SAFE, one action, to its right.
public struct FSHoldToConfirm: View {
    let title: String, designation: String
    let duration: Double
    let action: () -> Void
    @State private var progress: CGFloat = 0
    @State private var confirming = false
    @State private var done = 0
    @Environment(\.accessibilityReduceMotion) private var reduceMotion

    public init(_ title: String, designation: String, duration: Double = 2, action: @escaping () -> Void) {
        self.title = title; self.designation = designation; self.duration = duration; self.action = action
    }

    public var body: some View {
        FSPaletteReader { p in
            VStack(alignment: .leading, spacing: 6) {
                Label(title.uppercased(), systemImage: "bolt.horizontal").font(FS.heading().weight(.semibold))
                Text("\(designation) · \(Int(duration)) s").font(FS.readout(14, relativeTo: .footnote))
                Text("Keep holding").font(FS.label().weight(.semibold)).foregroundStyle(p.danger)
                    .opacity(progress > 0 ? 1 : 0)      // reserved, so the label doesn't jump when it appears
            }
            .padding(.horizontal, 16)
            .padding(.vertical, 12)
            .frame(maxWidth: .infinity, minHeight: FS.gloveTarget, alignment: .leading)
            // The progress lives in the background, sized by the control, never sizing it (a GeometryReader in the
            // stack would take every point it's offered).
            .background {
                GeometryReader { g in
                    ZStack(alignment: .bottomLeading) {
                        p.surface
                        p.danger.opacity(0.10).frame(width: g.size.width * progress)
                        p.rule.frame(height: 8)
                        p.danger.frame(width: g.size.width * progress, height: 8)
                    }
                }
            }
            .foregroundStyle(p.ink)
            .overlay(Rectangle().strokeBorder(p.ink, lineWidth: 2))
            .contentShape(Rectangle())
            .onLongPressGesture(minimumDuration: duration, maximumDistance: 40) {
                done += 1; progress = 0; action()
            } onPressingChanged: { pressing in
                if pressing { withAnimation(.linear(duration: duration)) { progress = 1 } }
                else { withAnimation(reduceMotion ? nil : .easeOut(duration: 0.16)) { progress = 0 } }
            }
            .sensoryFeedback(.success, trigger: done)
            .accessibilityElement(children: .ignore)
            .accessibilityLabel(Text("\(title) \(designation)"))
            .accessibilityHint(Text("Press and hold for \(Int(duration)) seconds, or use the action to confirm instead."))
            .accessibilityAddTraits(.isButton)
            .accessibilityAction(named: Text("\(title) with a confirmation")) { confirming = true }
            .confirmationDialog(Text("\(title) \(designation)?"), isPresented: $confirming, titleVisibility: .visible) {
                Button(title, role: .destructive) { done += 1; action() }
                Button("Cancel", role: .cancel) {}
            }
        }
    }
}

// MARK: - Freshness and the screen

/// How old a value may get before it shows as stale (product/data.md#live-telemetry).
public enum FSFreshness {
    public static let flight: TimeInterval = 2
    public static let weather: TimeInterval = 1800
    public static func isStale(since date: Date, limit: TimeInterval, now: Date = .now) -> Bool { now.timeIntervalSince(date) > limit }
    /// "0.4 s ago", "4 min ago", "2 h ago": the qualifier every live value carries.
    public static func age(since date: Date, now: Date = .now) -> String {
        let s = max(0, now.timeIntervalSince(date))
        if s < 10 { return String(format: "%.1f s ago", s) }
        if s < 60 { return "\(Int(s)) s ago" }
        if s < 3600 { return "\(Int(s / 60)) min ago" }
        return "\(Int(s / 3600)) h ago"
    }
}

extension View {
    /// Keeps the screen awake while this view is on screen: countdown and tracking screens only, released on leaving.
    /// Apps only: widgets and Live Activities can't hold the screen on (and can't reach UIApplication).
    @available(iOSApplicationExtension, unavailable)
    public func fsKeepsScreenOn() -> some View {
        #if os(iOS)
        return self
            .onAppear { UIApplication.shared.isIdleTimerDisabled = true }
            .onDisappear { UIApplication.shared.isIdleTimerDisabled = false }
        #else
        return self
        #endif
    }

    /// Field-size target: 96 pt for controls used at the pad (about 15 mm).
    public func fsFieldTarget() -> some View { frame(minWidth: FS.fieldTarget, minHeight: FS.fieldTarget) }
}
