// SPDX-License-Identifier: Apache-2.0 · Copyright 2026 Neer Patel
// A FusionSpace Live Activity, worked through: a flight from the pad to the landing site
// (product/mobile/glance/ios-live-activity.png, ios-dynamic-island.png). Generated by tools/build/kit_mobile.py from
// source/product/mobile/; edit there. Needs FusionSpaceColors.swift and FSComponents.swift. iOS 17+ only (ActivityKit).
//
// The rules it shows (product/mobile.md#glanceable-surfaces): the Dynamic Island is always black, so it uses the dark roles;
// every value has its unit and its age; the device's state is a word in a box (SAFE outlined, ARMED inverted); minimal
// shows live data, not a logo; updates stay small (4 KB for attributes and state together).
#if os(iOS) && canImport(ActivityKit)
import ActivityKit
import SwiftUI
import WidgetKit

public struct FSFlightAttributes: ActivityAttributes {
    public struct ContentState: Codable, Hashable, Sendable {
        public enum Phase: String, Codable, CaseIterable, Sendable { case pad, boost, coast, apogee, drogue, main, landed }
        public var phase: Phase
        public var armed: Bool
        public var altitudeFt: Int?        // AGL
        public var verticalFtS: Int?
        public var distanceFt: Int?        // from the phone
        public var bearingTrue: Int?
        public var padTime: Date?          // the countdown counts to the time the flier set, and says so
        public var liftoff: Date?
        public var sampledAt: Date         // the age shown is now minus this
    }
    public var flight: String             // "FLIGHT 04"
    public var designation: String        // "FS-VEGA-004"
    public var motor: String              // "K535W"
}

public struct FSFlightActivity: Widget {
    public init() {}
    public var body: some WidgetConfiguration {
        ActivityConfiguration(for: FSFlightAttributes.self) { context in
            FSFlightLockScreen(context: context)
                .activityBackgroundTint(FS.darkPalette.surface)
                .activitySystemActionForegroundColor(FS.darkPalette.ink)
                .environment(\.colorScheme, .dark)
        } dynamicIsland: { context in
            let s = context.state, d = FS.darkPalette
            return DynamicIsland {
                DynamicIslandExpandedRegion(.leading) {
                    FSIslandValue(label: "ALTITUDE", value: s.altitudeFt.map(fsNumber) ?? "—", unit: "ft AGL", big: true)
                }
                DynamicIslandExpandedRegion(.trailing) {
                    FSIslandValue(label: "FROM YOU", value: s.distanceFt.map(fsNumber) ?? "—", unit: "ft",
                                  note: s.bearingTrue.map { String(format: "%03d° T", $0) })
                }
                DynamicIslandExpandedRegion(.bottom) {
                    VStack(spacing: 8) {
                        FSPhaseStrip(phase: s.phase)
                        Text("\(context.attributes.designation) · link \(FSFreshness.age(since: s.sampledAt))")
                            .font(.caption).foregroundStyle(d.inkMuted).frame(maxWidth: .infinity, alignment: .leading)
                    }
                }
            } compactLeading: {
                Group {
                    if s.phase == .pad, let t = s.padTime {
                        // compact leading is about 52 pt: wider pushes the island over the clock
                        HStack(spacing: 0) {
                            Text("T−")
                            Text(timerInterval: Date.now...max(t, .now), countsDown: true).monospacedDigit()
                        }
                        .font(.custom("CascadiaMono-SemiBold", size: 13))
                        .frame(maxWidth: 52, alignment: .leading)
                    } else {
                        Text(s.phase.rawValue.uppercased())
                    }
                }
                .font(.custom("CascadiaMono-SemiBold", size: 15)).foregroundStyle(d.ink)
            } compactTrailing: {
                // inset from the island's rounded end, so the box's border is never cut by the curve
                if s.phase == .pad { FSIslandState(armed: s.armed).padding(.trailing, 4) }
                else { Text("\(s.altitudeFt.map(fsNumber) ?? "—") ft").font(.custom("CascadiaMono-SemiBold", size: 15)).foregroundStyle(d.ink) }
            } minimal: {
                VStack(spacing: 0) {
                    Text(s.altitudeFt.map { $0 >= 1000 ? String(format: "%.1fk", Double($0) / 1000) : "\($0)" } ?? "—")
                        .font(.custom("CascadiaMono-SemiBold", size: 12))
                    Text("ft").font(.system(size: 9)).foregroundStyle(d.inkMuted)
                }
                .foregroundStyle(d.ink)
            }
            .keylineTint(d.ink)
        }
    }
}

struct FSFlightLockScreen: View {
    let context: ActivityViewContext<FSFlightAttributes>
    var body: some View {
        let s = context.state, a = context.attributes, d = FS.darkPalette
        VStack(alignment: .leading, spacing: 10) {
            HStack {
                Text(header(s, a)).font(FS.label())
                Spacer()
                Text("LINK \(FSFreshness.age(since: s.sampledAt).replacingOccurrences(of: " ago", with: ""))").font(FS.label())
            }
            .foregroundStyle(d.inkMuted)
            if s.phase == .pad {
                HStack(alignment: .bottom) {
                    VStack(alignment: .leading, spacing: 2) {
                        if let t = s.padTime {
                            Text(timerInterval: Date.now...max(t, .now), countsDown: true).font(FS.readout(30, relativeTo: .title))
                            Text("to your pad time, \(t.formatted(date: .omitted, time: .shortened))").font(.caption).foregroundStyle(d.inkMuted)
                        }
                    }
                    Spacer()
                    FSStateBox(armed: s.armed)
                }
            } else {
                FSPhaseStrip(phase: s.phase)
                HStack(alignment: .bottom) {
                    FSIslandValue(label: "ALTITUDE", value: s.altitudeFt.map(fsNumber) ?? "—", unit: "ft AGL", big: true)
                    Spacer()
                    FSIslandValue(label: "FROM YOU", value: s.distanceFt.map(fsNumber) ?? "—", unit: "ft",
                                  note: s.bearingTrue.map { String(format: "%03d° T", $0) })
                }
            }
        }
        .foregroundStyle(d.ink)
        .padding(14)
    }
    private func header(_ s: FSFlightAttributes.ContentState, _ a: FSFlightAttributes) -> String {
        if let l = s.liftoff, s.phase != .pad, s.phase != .landed { return "\(a.flight) · T+\(Int(Date.now.timeIntervalSince(l))) s" }
        return "\(a.flight) · \(a.motor)"
    }
}

struct FSIslandValue: View {
    let label: String, value: String, unit: String
    var note: String? = nil
    var big = false
    var body: some View {
        let d = FS.darkPalette
        VStack(alignment: .leading, spacing: 2) {
            Text(label).font(FS.label()).foregroundStyle(d.inkMuted)
            HStack(alignment: .firstTextBaseline, spacing: 4) {
                Text(value).font(FS.readout(big ? 30 : 20, relativeTo: big ? .title : .headline))
                Text(unit).font(FS.label()).foregroundStyle(d.inkMuted)
            }
            if let note { Text(note).font(.caption).foregroundStyle(d.inkMuted) }
        }
        .foregroundStyle(d.ink)
        .accessibilityElement(children: .combine)
    }
}

/// PAD BOOST COAST APOGEE DROGUE MAIN LANDED: done in ink, now inverted, next faint.
struct FSPhaseStrip: View {
    let phase: FSFlightAttributes.ContentState.Phase
    var body: some View {
        let d = FS.darkPalette, all = FSFlightAttributes.ContentState.Phase.allCases, i = all.firstIndex(of: phase) ?? 0
        HStack(spacing: 0) {
            ForEach(Array(all.enumerated()), id: \.offset) { j, p in
                Text(p.rawValue.uppercased())
                    .font(.custom("CascadiaMono-Regular", size: 8.5)).lineLimit(1).minimumScaleFactor(0.7)
                    .frame(maxWidth: .infinity).padding(.vertical, 4)
                    .foregroundStyle(j == i ? d.canvas : (j < i ? d.ink : d.inkFaint))
                    .background(j == i ? d.ink : Color.clear)
            }
        }
        .overlay(Rectangle().strokeBorder(d.ruleStrong, lineWidth: 1))
        .accessibilityElement(children: .ignore)
        .accessibilityLabel(Text("Phase: \(phase.rawValue)"))
    }
}

struct FSIslandState: View {
    let armed: Bool
    var body: some View {
        Text(armed ? "ARMED" : "SAFE").font(.custom("CascadiaMono-SemiBold", size: 10))
            .padding(.horizontal, 4).padding(.vertical, 2)
            .foregroundStyle(armed ? FS.onDangerFill : FS.darkPalette.ink)
            .background(armed ? FS.dangerFill : Color.clear)
            .overlay(Rectangle().strokeBorder(armed ? FS.dangerFill : FS.darkPalette.ink, lineWidth: 1.5))
    }
}

/// US-style grouping for the screen: 1,352.
func fsNumber(_ v: Int) -> String { v.formatted(.number.grouping(.automatic)) }
#endif
