# FusionSpace
[colors.primary]
background = "#0B0F1C"
foreground = "#E6E8EF"
[colors.cursor]
cursor = "#768DF5"
[colors.selection]
background = "#2A3248"
[colors.normal]
black = "#141A2B"
red = "#FB8083"
green = "#6AD5B6"
yellow = "#F5AF20"
blue = "#768DF5"
magenta = "#ED89D2"
cyan = "#8FD3E8"
white = "#D6DAE4"
[colors.bright]
black = "#566079"
red = "#FFA9AB"
green = "#9BE8D0"
yellow = "#FFCB66"
blue = "#CAD7FF"
magenta = "#F5B4E3"
cyan = "#B9E8F5"
white = "#FFFFFF"
