# FusionSpace
background #0B0F1C
foreground #E6E8EF
cursor #768DF5
selection_background #2A3248
color0 #141A2B
color1 #F07A6A
color2 #8FD1A8
color3 #DA7C30
color4 #768DF5
color5 #A188CB
color6 #8FD3E8
color7 #D6DAE4
color8 #566079
color9 #FF9C8C
color10 #B2E5C5
color11 #FFD2A1
color12 #CAD7FF
color13 #E2D6F5
color14 #B9E8F5
color15 #FFFFFF
