// SPDX-License-Identifier: Apache-2.0 · Copyright 2026 Neer Patel
// FusionSpace complications for watchOS, worked through: the way to a landed rocket on every accessory family
// (product/watch/faces/watchos-complications.png). Generated by tools/build/kit_watch.py from source/product/watch/; edit
// there. Needs FusionSpaceColors.swift and FSWatch.swift. watchOS 10+.
//
// Rules (product/watch.md#complications-smart-stack-and-tiles): one value with its unit and its age; meaning in words and
// shapes, so it reads in accented rendering where the system tints everything; the value is the accent group; no logo.
#if os(watchOS)
import RelevanceKit
import SwiftUI
import WidgetKit

public struct FSFindEntry: TimelineEntry, Sendable {
    public let date: Date
    public let fixedAt: Date
    public let name: String                 // the rocket's external name: "Vega"
    public let phase: String                // "LANDED"
    public let distanceFt: Int
    public let bearingTrue: Int
    public static let example = FSFindEntry(date: .now, fixedAt: .now.addingTimeInterval(-4), name: "Vega", phase: "LANDED",
                                            distanceFt: 1352, bearingTrue: 62)
}

public struct FSFindProvider: TimelineProvider {
    public init() {}
    public func placeholder(in context: Context) -> FSFindEntry { .example }
    public func getSnapshot(in context: Context, completion: @escaping (FSFindEntry) -> Void) { completion(.example) }
    public func getTimeline(in context: Context, completion: @escaping (Timeline<FSFindEntry>) -> Void) {
        // The app reloads the timeline when a new fix arrives (WidgetCenter.shared.reloadTimelines(ofKind:)). Two entries per
        // fix: the fix itself, whose age counts up on its own, and the moment it goes stale, when the view says so.
        let e = FSFindEntry.example
        let stale = FSFindEntry(date: e.fixedAt.addingTimeInterval({{FIND_STALE_S}} + 1), fixedAt: e.fixedAt, name: e.name, phase: e.phase,
                                distanceFt: e.distanceFt, bearingTrue: e.bearingTrue)
        completion(Timeline(entries: [e, stale], policy: .never))
    }
    public func relevance() async -> WidgetRelevance<Void> {
        // Ranked high in the Smart Stack only while a rocket is out and unfound.
        WidgetRelevance([WidgetRelevanceAttribute(context: RelevantContext.date(from: .now, to: .now.addingTimeInterval(2 * 3600)))])
    }
}

struct FSFindComplication: View {
    let entry: FSFindEntry
    @Environment(\.widgetFamily) private var family
    @Environment(\.widgetRenderingMode) private var mode
    private var d: FSPalette { FS.darkPalette }
    private var stale: Bool { FSFreshness.isStale(since: entry.fixedAt, limit: {{FIND_STALE_S}}, now: entry.date) }
    private var bearing: String { String(format: "%03d°\u{00A0}T", entry.bearingTrue) }
    /// The fix's age, counting up on its own between timeline entries and in Always On ("4 sec", "1 min"): computed once
    /// per entry, it would still say "4 s" a minute later.
    private var age: Text { Text(entry.fixedAt, style: .relative) }
    private var distanceForms: [String] {
        let n = entry.distanceFt
        return [n.formatted(), "\(n)", (Double(n) / 1000).formatted(.number.precision(.fractionLength(1))) + "k"]
    }
    /// One sentence for VoiceOver on the face, whatever the family shows.
    private var spoken: Text {
        let what = "\(entry.name), \(entry.phase.lowercased()), \(entry.distanceFt.formatted()) feet, bearing \(entry.bearingTrue) degrees true"
        return stale ? Text("\(what), fix stale") : Text("\(what), fix \(age) old")
    }

    var body: some View {
        content
            .accessibilityElement(children: .ignore)
            .accessibilityLabel(spoken)
    }

    @ViewBuilder private var content: some View {
        switch family {
        case .accessoryCircular:
            VStack(spacing: 0) {
                // The complication can't know which way the wrist points, so the arrow is the bearing from north.
                // stale: the arrow outlined and the number muted (no room for the word)
                FSBearingArrow(relativeDegrees: Double(entry.bearingTrue), outline: stale).frame(width: 22, height: 22)
                // the first that fits the circle, never cut with "…": 1,352 / 12,345, then 12345, then 12.3k
                ViewThatFits(in: .horizontal) {
                    ForEach(distanceForms, id: \.self) { Text($0).lineLimit(1).fixedSize() }
                }
                .font(FS.readout(13, relativeTo: .caption)).foregroundStyle(stale ? d.inkMuted : d.ink).widgetAccentable()
                Text("ft").font(.system(size: 8))
            }
        case .accessoryCorner:
            FSBearingArrow(relativeDegrees: Double(entry.bearingTrue), outline: stale)
                // the curved label holds about 17 characters before the system cuts it with "…": stale drops the bearing
                .widgetLabel { Text(stale ? "Stale · \(entry.distanceFt.formatted())\u{00A0}ft" : "\(entry.distanceFt.formatted())\u{00A0}ft · \(bearing)") }
        case .accessoryInline:
            Text("\(entry.name)\(stale ? " stale" : "") \(entry.distanceFt.formatted())\u{00A0}ft \(bearing)")
        default:
            VStack(alignment: .leading, spacing: 1) {
                HStack {
                    Text("\(entry.name.uppercased()) · \(entry.phase)")
                    Spacer()
                    if stale { Text("STALE") } else { age.monospacedDigit().multilineTextAlignment(.trailing) }  // a relative date takes the spare width
                }
                .font(FS.label()).foregroundStyle(d.inkMuted)
                HStack(alignment: .firstTextBaseline, spacing: 4) {
                    Text(entry.distanceFt.formatted()).font(FS.readout(24, relativeTo: .title3)).widgetAccentable()
                    Text("ft").font(FS.label()).foregroundStyle(d.inkMuted)
                }
                .foregroundStyle(stale ? d.inkMuted : d.ink)
                Text("\(bearing) from you").font(.caption2).foregroundStyle(d.inkMuted)
            }
        }
    }
}

public struct FSFindWidget: Widget {
    public init() {}
    public var body: some WidgetConfiguration {
        StaticConfiguration(kind: "co.fusionspace.track.find", provider: FSFindProvider()) { entry in
            FSFindComplication(entry: entry).containerBackground(for: .widget) { Color.clear }
        }
        .configurationDisplayName("Find the rocket")
        .description("Distance and bearing to the rocket, with the age of its fix.")
        .supportedFamilies([.accessoryCircular, .accessoryCorner, .accessoryRectangular, .accessoryInline])
    }
}
#endif
