// SPDX-License-Identifier: Apache-2.0 · Copyright 2026 Neer Patel
// FusionSpace parts for watchOS. Generated by tools/build/kit_watch.py from source/product/watch/; edit there.
// Needs FusionSpaceColors.swift (product/tokens/) and FSComponents.swift (product/mobile/swiftui/). watchOS 10+.
//
// A watch finds, glances and taps the wrist (product/watch.md). It never commands hardware: nothing here sends ARM, SAFE,
// FIRE or a configuration change. Screens use the dark roles always: a watch is an emissive screen on a black face.
import SwiftUI
#if os(watchOS)
import WatchKit
#endif

// MARK: - The way to the rocket

/// A nose cone pointing at the rocket, relative to where the wrist points, on a ring with the wearer's heading at the top.
/// Outline only when the screen is dimmed (Always On).
public struct FSBearingArrow: View {
    let degrees: Double
    let outline: Bool
    public init(relativeDegrees: Double, outline: Bool = false) { self.degrees = relativeDegrees; self.outline = outline }

    public var body: some View {
        let d = FS.darkPalette
        Canvas { ctx, size in
            let c = CGPoint(x: size.width / 2, y: size.height / 2), r = min(size.width, size.height) / 2 - 4
            ctx.stroke(Path(ellipseIn: CGRect(x: c.x - r, y: c.y - r, width: 2 * r, height: 2 * r)), with: .color(d.ruleStrong), lineWidth: 1.5)
            for a in stride(from: 0.0, to: 360, by: 30) {
                let r0 = r - (a == 0 ? 7 : 4), t = a * .pi / 180
                var p = Path()
                p.move(to: CGPoint(x: c.x + r0 * sin(t), y: c.y - r0 * cos(t)))
                p.addLine(to: CGPoint(x: c.x + r * sin(t), y: c.y - r * cos(t)))
                ctx.stroke(p, with: .color(d.inkMuted), lineWidth: a == 0 ? 2 : 1)
            }
            var g = ctx
            g.translateBy(x: c.x, y: c.y); g.rotate(by: .degrees(degrees)); g.translateBy(x: -c.x, y: -c.y)
            let cone = FSBearingArrow.noseCone(tip: CGPoint(x: c.x, y: c.y - r + 10), length: r * 0.78, radius: r * 0.3)
            if outline { g.stroke(cone, with: .color(d.ink), lineWidth: 2) } else { g.fill(cone, with: .color(d.ink)) }
            var shaft = Path()
            shaft.move(to: CGPoint(x: c.x, y: c.y - r + 10 + r * 0.78)); shaft.addLine(to: CGPoint(x: c.x, y: c.y + r * 0.45))
            g.stroke(shaft, with: .color(d.ink), lineWidth: outline ? 2 : 4)
        }
        .aspectRatio(1, contentMode: .fit)
        .accessibilityHidden(true)
    }

    /// The Von Kármán profile (LD-Haack, C = 0), the brand mark's main cone, as the arrowhead.
    static func noseCone(tip: CGPoint, length L: CGFloat, radius R: CGFloat) -> Path {
        let ys: [(CGFloat, CGFloat)] = (0...20).map { i in
            let x = L * CGFloat(i) / 20, th = acos(1 - 2 * x / L)
            return (x, R / sqrt(.pi) * sqrt(th - sin(2 * th) / 2))
        }
        var p = Path()
        p.move(to: CGPoint(x: tip.x - ys.last!.1, y: tip.y + L))
        for (x, y) in ys.reversed() { p.addLine(to: CGPoint(x: tip.x - y, y: tip.y + x)) }
        for (x, y) in ys { p.addLine(to: CGPoint(x: tip.x + y, y: tip.y + x)) }
        p.closeSubpath()
        return p
    }
}

/// Find: the way to a landed rocket, how far, the bearing in degrees true, and how old the fix is. Dims for Always On:
/// outlines, muted, the age replaced by the time it was true ("as of 9:41"), redrawn once a minute.
public struct FSWatchFind: View {
    let distanceFt: Int, bearingTrue: Double, headingTrue: Double?, fixedAt: Date
    let onFound: () -> Void
    @Environment(\.isLuminanceReduced) private var dimmed

    public init(distanceFt: Int, bearingTrue: Double, headingTrue: Double?, fixedAt: Date, onFound: @escaping () -> Void) {
        self.distanceFt = distanceFt; self.bearingTrue = bearingTrue; self.headingTrue = headingTrue; self.fixedAt = fixedAt; self.onFound = onFound
    }

    public var body: some View {
        let d = FS.darkPalette
        TimelineView(.periodic(from: .now, by: dimmed ? 60 : 1)) { tl in
            // The largest arrow that leaves room for everything else: fits every case size without clipping.
            ViewThatFits(in: .vertical) {
                ForEach([104, 84, 64, 48], id: \.self) { size in screen(arrow: CGFloat(size), now: tl.date) }
            }
            .accessibilityElement(children: .contain)
        }
        .navigationTitle("Find")
        .fsWatchHapticOnStale(fixedAt: fixedAt, limit: FSFreshness.flight * 30)
    }

    private func screen(arrow: CGFloat, now: Date) -> some View {
        let d = FS.darkPalette
        return VStack(spacing: 2) {
            // Without a heading (no compass, or not calibrated) the arrow points to the bearing from north, and says so.
            FSBearingArrow(relativeDegrees: bearingTrue - (headingTrue ?? 0), outline: dimmed).frame(width: arrow, height: arrow)
            HStack(alignment: .firstTextBaseline, spacing: 4) {
                Text(distanceFt.formatted()).font(FS.readout(32, relativeTo: .title))
                Text("ft").font(FS.label()).foregroundStyle(d.inkMuted)
            }
            .foregroundStyle(dimmed ? d.inkMuted : d.ink)
            .lineLimit(1).minimumScaleFactor(0.7)
            .accessibilityElement(children: .ignore)
            .accessibilityLabel(Text("Rocket \(distanceFt.formatted()) feet away, bearing \(Int(bearingTrue)) degrees true"))
            .accessibilityValue(Text(FSFreshness.age(since: fixedAt, now: now)))
            Text(qualifier(now: now)).font(FS.label()).foregroundStyle(d.inkMuted)
                .multilineTextAlignment(.center).fixedSize(horizontal: false, vertical: true)
            // The primary action, full width in the content (a bottom-bar item would sit over the text above).
            // Always On shows it as unavailable instead of removing it.
            Button(action: onFound) {
                Text("Found it").frame(maxWidth: .infinity).foregroundStyle(dimmed ? d.inkMuted : d.onAction)
            }
            .buttonStyle(.borderedProminent)
            .disabled(dimmed)
            .padding(.top, 2)
        }
        .frame(maxWidth: .infinity)
    }

    private func qualifier(now: Date) -> String {
        let bearing = String(format: "%03d°\u{00A0}T", Int(bearingTrue.rounded()) % 360)
        // Two short lines rather than one long one: the smallest watch is 162 pt wide.
        if dimmed { return "\(bearing)\nas of \(fixedAt.formatted(date: .omitted, time: .shortened))" }
        return "\(bearing)" + (headingTrue == nil ? " · from north" : "") + "\nfix \(FSFreshness.age(since: fixedAt, now: now))"
    }
}

// MARK: - State and alerts

/// The device's state at the pad, read only: SAFE outlined or ARMED inverted, then the channels in order. Nothing here
/// sends a command; safing is the airframe switch or the phone.
public struct FSWatchState: View {
    public struct Channel: Identifiable, Sendable {
        public let id: Int; let name: String; let state: FSSignal; let word: String
        public init(_ n: Int, _ name: String, _ state: FSSignal, _ word: String) { id = n; self.name = name; self.state = state; self.word = word }
    }
    let designation: String, armed: Bool, channels: [Channel], linkAge: String
    public init(designation: String, armed: Bool, channels: [Channel], linkAge: String) {
        self.designation = designation; self.armed = armed; self.channels = channels; self.linkAge = linkAge
    }
    public var body: some View {
        // The first layout that fits wins: full, then tighter, then scrolling (large text sizes). Nothing is ever cut.
        ViewThatFits(in: .vertical) {
            content(compact: false)
            content(compact: true)
            content(compact: true, side: true)
            ScrollView { content(compact: false) }
        }
        .environment(\.fsTheme, .dark)
    }
    private func content(compact: Bool, side: Bool = false) -> some View {
        let d = FS.darkPalette
        let box = Text(armed ? "ARMED" : "SAFE")
            .font(.custom("CascadiaMono-SemiBold", size: compact ? 18 : 22, relativeTo: .title3))
            .padding(.horizontal, compact ? 6 : 10).padding(.vertical, compact ? 3 : 5)
            .foregroundStyle(armed ? FS.onDangerFill : d.ink)
            .background(armed ? FS.dangerFill : Color.clear)
            .overlay(Rectangle().strokeBorder(armed ? FS.dangerFill : d.ink, lineWidth: 3))
        let link = Text("\(designation) · \(linkAge)").font(FS.label()).foregroundStyle(d.inkMuted).lineLimit(1).minimumScaleFactor(0.8)
            .accessibilityLabel(Text("\(designation), link \(linkAge)"))
        return VStack(spacing: compact ? 2 : 4) {
            if side {
                // the smallest watches: the designation beside the box saves a line
                HStack(spacing: 6) {
                    box
                    VStack(alignment: .leading, spacing: 0) {
                        Text(designation).font(FS.label()).lineLimit(1).minimumScaleFactor(0.7)
                        Text(linkAge).font(FS.label()).foregroundStyle(d.inkMuted)
                    }
                    .accessibilityElement(children: .ignore)
                    .accessibilityLabel(Text("\(designation), link \(linkAge)"))
                }
            } else {
                box
                link
            }
            ForEach(channels) { ch in
                // the channel and its state on one line, or the state under the name when both don't fit
                ViewThatFits(in: .horizontal) {
                    HStack(spacing: 4) {
                        Text("\(ch.id) \(ch.name)").font(FS.label()).fixedSize()
                        Spacer(minLength: 4)
                        FSStatus(ch.word, signal: ch.state, minHeight: 20)
                    }
                    VStack(alignment: .leading, spacing: 2) {
                        Text("\(ch.id) \(ch.name)").font(FS.label())
                        FSStatus(ch.word, signal: ch.state, minHeight: 20)
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                }
            }
            Text(compact ? "Safe: switch or phone." : "Safe it with the switch or phone.").font(.caption2).foregroundStyle(d.inkMuted)
                .multilineTextAlignment(.center).fixedSize(horizontal: false, vertical: true)
        }
        .foregroundStyle(d.ink)
        .scenePadding(.horizontal)
    }
}

/// A configured charge that didn't fire: full screen in Flare, before anything else, with the wrist pattern repeating until
/// it's acknowledged. Acknowledging stops the taps, not the device's beeper or LED.
public struct FSWatchUnfired: View {
    let channel: String
    let onAcknowledge: () -> Void
    public init(channel: String, onAcknowledge: @escaping () -> Void) { self.channel = channel; self.onAcknowledge = onAcknowledge }
    public var body: some View {
        ViewThatFits(in: .vertical) {
            content(compact: false)
            content(compact: true)
            content(compact: true, tight: true)
            ScrollView { content(compact: false) }
        }
        .foregroundStyle(FS.onDangerFill)
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .background(FS.dangerFill.ignoresSafeArea())
        .onAppear { FSWristEvent.unfired.play() }
    }
    private func content(compact: Bool, tight: Bool = false) -> some View {
        VStack(spacing: compact ? 2 : 4) {
            HStack(spacing: tight ? 4 : 6) {
                Image(systemName: "exclamationmark.triangle")
                Text(tight ? "UNFIRED \(channel)" : "UNFIRED")
                    .font(.custom("CascadiaMono-SemiBold", size: tight ? 15 : (compact ? 20 : 24), relativeTo: .title2))
                    .lineLimit(1).minimumScaleFactor(0.8)
            }
            .accessibilityElement(children: .combine)
            if !tight { Text(channel).font(FS.readout(compact ? 16 : 18, relativeTo: .headline)) }
            Text("Approach as live. Disarm before handling.").font(compact ? .caption2 : .footnote)
                .multilineTextAlignment(.center).fixedSize(horizontal: false, vertical: true)
            Button("OK", action: onAcknowledge).padding(.top, compact ? 0 : 4)
        }
        .scenePadding(.horizontal)
        .accessibilityElement(children: .contain)
        .accessibilityLabel(Text("Unfired charge, \(channel). Approach as live. Disarm before handling."))
    }
}

// MARK: - The wrist language

/// One tap pattern per meaning, mirroring the device's beep language (product/embedded.md#beeps). Nothing routine taps the
/// wrist: no tap for an altitude update or a phase the flier can see coming. These play while the app is on screen; watchOS
/// plays nothing from the background outside a workout session, so a background alarm arrives as a notification instead.
public enum FSWristEvent: CaseIterable, Sendable {
    case liftoff, mainOut, landedAllFired, unfired, linkLost, linkBack, arrived

    #if os(watchOS)
    /// The system pattern for each event; unfired repeats three times, like the device's rapid triple.
    var pattern: [WKHapticType] {
        switch self {
        case .liftoff: return [.start]
        case .mainOut: return [.click]
        case .landedAllFired: return [.success]
        case .unfired: return [.failure, .failure, .failure]
        case .linkLost: return [.retry]
        case .linkBack: return [.click]
        case .arrived: return [.notification]
        }
    }
    #endif

    public func play() {
        #if os(watchOS)
        for (i, h) in pattern.enumerated() {
            DispatchQueue.main.asyncAfter(deadline: .now() + Double(i) * 0.6) { WKInterfaceDevice.current().play(h) }
        }
        #endif
    }
}

extension View {
    /// Taps the link-lost pattern once when the fix gets older than `limit` seconds, and link-back when it recovers.
    func fsWatchHapticOnStale(fixedAt: Date, limit: TimeInterval) -> some View {
        modifier(FSStaleHaptic(fixedAt: fixedAt, limit: limit))
    }
}

private struct FSStaleHaptic: ViewModifier {
    let fixedAt: Date, limit: TimeInterval
    @State private var stale = false
    func body(content: Content) -> some View {
        content.task(id: fixedAt) {
            while !Task.isCancelled {
                let now = FSFreshness.isStale(since: fixedAt, limit: limit)
                if now != stale { stale = now; (now ? FSWristEvent.linkLost : FSWristEvent.linkBack).play() }
                try? await Task.sleep(for: .seconds(1))
            }
        }
    }
}
