// FusionSpace metadata for the Next.js App Router (app/layout.tsx). Generated by tools/build/kit_site.py.
// Rev C icons and colours; copy the files in this folder first (see README.md).
import type { Metadata, Viewport } from "next";

const NAME = "FusionSpace";   // always one word, like the wordmark. The site says "Fusion Space" today: change its body copy too.
const DESCRIPTION = `${NAME} builds free, polished tools for the high-power rocketry community. Home of the HPR Motor Finder, with more rocketry tools on the way.`;

export const metadata: Metadata = {
  metadataBase: new URL("https://fusionspace.co"),
  title: { default: NAME, template: `%s · ${NAME}` },
  description: DESCRIPTION,
  applicationName: NAME,
  manifest: "/manifest.webmanifest",
  // app/icon.svg and app/apple-icon.png are picked up automatically; favicon.ico goes in app/ as well.
  openGraph: { title: NAME, description: DESCRIPTION, url: "/", siteName: NAME, type: "website",
                images: [{ url: "/og.png", width: 1200, height: 630, alt: NAME }] },
  twitter: { card: "summary_large_image", title: NAME, description: DESCRIPTION, images: ["/og.png"] },
};

export const viewport: Viewport = {
  // Brand Paper and Void. If the site keeps a pure white light theme, use "#ffffff" for the light entry.
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#F3F4F7" },
    { media: "(prefers-color-scheme: dark)", color: "#0B0F1C" },
  ],
  colorScheme: "light dark",
};
