// FusionSpace product colours for SwiftUI. Generated by tools/build/kit_product.py; edit there, not here.
// Light and dark follow the system appearance; the field theme is used for Increase Contrast.
import SwiftUI
#if canImport(UIKit)
import UIKit
#endif

public enum FS {
    // Semantic roles
    /// Page and screen background
    public static let canvas = dynamic(light: 0xF3F4F7, dark: 0x0B0F1C, increasedContrast: 0xFFFFFF)
    /// Raised panels, inputs, tables, dialogs (separated by rules, never shadows)
    public static let surface = dynamic(light: 0xFFFFFF, dark: 0x141A2B, increasedContrast: 0xFFFFFF)
    /// Hairlines between rows, sections and cells (decoration: no contrast minimum)
    public static let rule = dynamic(light: 0xD6DAE4, dark: 0x2A3248, increasedContrast: 0x98A1B8)
    /// Control borders and chart axes (3:1 against canvas and surface)
    public static let ruleStrong = dynamic(light: 0x566079, dark: 0x6D7790, increasedContrast: 0x0B0F1C)
    /// Text, primary lines, measured data
    public static let ink = dynamic(light: 0x0B0F1C, dark: 0xF3F4F7, increasedContrast: 0x0B0F1C)
    /// Secondary text: labels, units, captions, sources
    public static let inkMuted = dynamic(light: 0x566079, dark: 0x98A1B8, increasedContrast: 0x2A3248)
    /// Disabled text, placeholders, hatching (not for anything that must be read)
    public static let inkFaint = dynamic(light: 0x98A1B8, dark: 0x566079, increasedContrast: 0x566079)
    /// Links, selection, focus, the one interactive accent
    public static let action = dynamic(light: 0x3350D6, dark: 0x768DF5, increasedContrast: 0x3350D6)
    /// Text on an action fill
    public static let onAction = dynamic(light: 0xFFFFFF, dark: 0x0B0F1C, increasedContrast: 0xFFFFFF)
    /// Focus ring (2 px outline, 2 px offset)
    public static let focus = dynamic(light: 0x3350D6, dark: 0x768DF5, increasedContrast: 0x3350D6)
    /// Danger ink: text, icons and lines
    public static let danger = dynamic(light: 0xAC001E, dark: 0xFB8083, increasedContrast: 0xAC001E)
    /// Caution ink: text, icons and lines
    public static let caution = dynamic(light: 0xB34F0C, dark: 0xF5AF20, increasedContrast: 0xB34F0C)
    /// Normal ink: text, icons and lines
    public static let ok = dynamic(light: 0x0A6355, dark: 0x6AD5B6, increasedContrast: 0x0A6355)
    /// Predicted, simulated or forecast data (always dashed or hatched too)
    public static let predicted = dynamic(light: 0xA22488, dark: 0xED89D2, increasedContrast: 0xA22488)
    // Signal fills: the same on every background, like a safety sign
    public static let dangerFill = Color(hex: 0xAC001E)
    public static let onDangerFill = Color(hex: 0xFFFFFF)
    public static let cautionFill = Color(hex: 0xF5AF20)
    public static let onCautionFill = Color(hex: 0x0B0F1C)
    public static let okFill = Color(hex: 0x0A6355)
    public static let onOkFill = Color(hex: 0xFFFFFF)
    public static let infoFill = Color(hex: 0x3350D6)
    public static let onInfoFill = Color(hex: 0xFFFFFF)
    /// Identity only, always leading to trailing. Never a status or a data scale.
    public static let gradient = LinearGradient(colors: [Color(hex: 0xDA7C30), Color(hex: 0xD07D7A), Color(hex: 0xA188CB), Color(hex: 0x768DF5)], startPoint: .leading, endPoint: .trailing)

    // Type: brand faces for titles, labels and numbers; body text stays in the system font (Dynamic Type).
    public static func title(_ style: Font.TextStyle = .title2) -> Font { .custom("CascadiaMono-SemiBold", size: 28, relativeTo: style) }
    public static func label() -> Font { .custom("CascadiaMono-Regular", size: 12, relativeTo: .caption) }
    public static func readout(_ size: CGFloat = 28, relativeTo style: Font.TextStyle = .title) -> Font { .custom("CascadiaMono-Regular", size: size, relativeTo: style).monospacedDigit() }
    public static func heading() -> Font { .custom("Archivo-SemiBold", size: 17, relativeTo: .headline) }

    public static let fieldTarget: CGFloat = 64   // pt, controls used at the pad

    static func dynamic(light: UInt32, dark: UInt32, increasedContrast: UInt32) -> Color {
        #if canImport(UIKit)
        return Color(UIColor { t in
            if t.accessibilityContrast == .high && t.userInterfaceStyle != .dark { return UIColor(hex: increasedContrast) }
            return UIColor(hex: t.userInterfaceStyle == .dark ? dark : light)
        })
        #else
        return Color(hex: light)
        #endif
    }
}

extension Color {
    init(hex: UInt32) { self.init(.sRGB, red: Double((hex >> 16) & 0xFF) / 255, green: Double((hex >> 8) & 0xFF) / 255, blue: Double(hex & 0xFF) / 255) }
}
#if canImport(UIKit)
extension UIColor {
    convenience init(hex: UInt32) { self.init(red: CGFloat((hex >> 16) & 0xFF) / 255, green: CGFloat((hex >> 8) & 0xFF) / 255, blue: CGFloat(hex & 0xFF) / 255, alpha: 1) }
}
#endif
