/* SPDX-License-Identifier: Apache-2.0 · Copyright 2026 Neer Patel */
/* FusionSpace product colors for firmware (TFT, LVGL). Generated by tools/build/kit_product.py; edit there. */
#ifndef FUSIONSPACE_UI_H
#define FUSIONSPACE_UI_H

/* Screens on a device use the dark roles: emissive panels at the pad read best as light marks on Void,
   and Void pixels draw no power on OLED. RGB888 for LVGL (lv_color_hex), RGB565 for TFT_eSPI and friends. */

#define FS_CANVAS_RGB888 0x0B0F1Cu   /* Page and screen background */
#define FS_CANVAS_RGB565 0x0863u
#define FS_SURFACE_RGB888 0x141A2Bu   /* Raised panels, inputs, tables, dialogs (separated by rules, never shadows) */
#define FS_SURFACE_RGB565 0x10C5u
#define FS_RULE_RGB888 0x2A3248u   /* Hairlines between rows, sections and cells (decoration: no contrast minimum) */
#define FS_RULE_RGB565 0x2989u
#define FS_RULE_STRONG_RGB888 0x6D7790u   /* Control borders and chart axes (3:1 against canvas and surface) */
#define FS_RULE_STRONG_RGB565 0x6BB2u
#define FS_INK_RGB888 0xF3F4F7u   /* Text, primary lines, measured data */
#define FS_INK_RGB565 0xF7BEu
#define FS_INK_MUTED_RGB888 0x98A1B8u   /* Secondary text: labels, units, captions, sources */
#define FS_INK_MUTED_RGB565 0x9D17u
#define FS_INK_FAINT_RGB888 0x566079u   /* Disabled text and hatching (not for anything that must be read, placeholders included) */
#define FS_INK_FAINT_RGB565 0x530Fu
#define FS_ACTION_RGB888 0x768DF5u   /* Links, selection, focus, the one interactive accent */
#define FS_ACTION_RGB565 0x747Eu
#define FS_ON_ACTION_RGB888 0x0B0F1Cu   /* Text on an action fill */
#define FS_ON_ACTION_RGB565 0x0863u
#define FS_FOCUS_RGB888 0x768DF5u   /* Focus ring (2 px outline, 2 px offset) */
#define FS_FOCUS_RGB565 0x747Eu
#define FS_DANGER_RGB888 0xFB8083u   /* Danger ink: text, icons and lines */
#define FS_DANGER_RGB565 0xFC10u
#define FS_CAUTION_RGB888 0xF5AF20u   /* Caution ink: text, icons and lines */
#define FS_CAUTION_RGB565 0xF564u
#define FS_OK_RGB888 0x6AD5B6u   /* Normal ink: text, icons and lines */
#define FS_OK_RGB565 0x6EB6u
#define FS_PREDICTED_RGB888 0xED89D2u   /* Predicted, simulated or forecast data (always dashed or hatched too) */
#define FS_PREDICTED_RGB565 0xEC5Au
#define FS_DANGER_FILL_RGB888 0xAC001Eu
#define FS_DANGER_FILL_RGB565 0xA803u
#define FS_ON_DANGER_FILL_RGB888 0xFFFFFFu
#define FS_ON_DANGER_FILL_RGB565 0xFFFFu
#define FS_CAUTION_FILL_RGB888 0xF5AF20u
#define FS_CAUTION_FILL_RGB565 0xF564u
#define FS_ON_CAUTION_FILL_RGB888 0x0B0F1Cu
#define FS_ON_CAUTION_FILL_RGB565 0x0863u
#define FS_OK_FILL_RGB888 0x0A6355u
#define FS_OK_FILL_RGB565 0x0B0Au
#define FS_ON_OK_FILL_RGB888 0xFFFFFFu
#define FS_ON_OK_FILL_RGB565 0xFFFFu
#define FS_INFO_FILL_RGB888 0x3350D6u
#define FS_INFO_FILL_RGB565 0x329Au
#define FS_ON_INFO_FILL_RGB888 0xFFFFFFu
#define FS_ON_INFO_FILL_RGB565 0xFFFFu

/* Flash rates (NASA-STD-3001 Vol 2): the only two allowed. Period ms and on-time ms. */
#define FS_FLASH_WARNING_PERIOD_MS 333u
#define FS_FLASH_WARNING_ON_MS 166u
#define FS_FLASH_ADVISORY_PERIOD_MS 1250u
#define FS_FLASH_ADVISORY_ON_MS 875u

#endif
