// SPDX-License-Identifier: Apache-2.0 · Copyright 2026 Neer Patel
// FusionSpace product colors for Jetpack Compose. Generated by tools/build/kit_product.py; edit there, not here.
// A static brand scheme: no dynamic color for anything that carries meaning (Material allows a static scheme).
package co.fusionspace.design

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

@Immutable
data class FsColors(
    val canvas: Color,
    val surface: Color,
    val rule: Color,
    val ruleStrong: Color,
    val ink: Color,
    val inkMuted: Color,
    val inkFaint: Color,
    val action: Color,
    val onAction: Color,
    val focus: Color,
    val danger: Color,
    val caution: Color,
    val ok: Color,
    val predicted: Color,
    val dangerFill: Color,
    val cautionFill: Color,
    val okFill: Color,
    val infoFill: Color,
    val onDangerFill: Color,
    val onCautionFill: Color,
    val onOkFill: Color,
    val onInfoFill: Color,
)

val LightFsColors = FsColors(
    canvas = Color(0xFFF3F4F7),
    surface = Color(0xFFFFFFFF),
    rule = Color(0xFFD6DAE4),
    ruleStrong = Color(0xFF566079),
    ink = Color(0xFF0B0F1C),
    inkMuted = Color(0xFF566079),
    inkFaint = Color(0xFF98A1B8),
    action = Color(0xFF3350D6),
    onAction = Color(0xFFFFFFFF),
    focus = Color(0xFF3350D6),
    danger = Color(0xFFAC001E),
    caution = Color(0xFFB34F0C),
    ok = Color(0xFF0A6355),
    predicted = Color(0xFFA22488),
    dangerFill = Color(0xFFAC001E),
    cautionFill = Color(0xFFF5AF20),
    okFill = Color(0xFF0A6355),
    infoFill = Color(0xFF3350D6),
    onDangerFill = Color(0xFFFFFFFF),
    onCautionFill = Color(0xFF0B0F1C),
    onOkFill = Color(0xFFFFFFFF),
    onInfoFill = Color(0xFFFFFFFF),
)

val DarkFsColors = FsColors(
    canvas = Color(0xFF0B0F1C),
    surface = Color(0xFF141A2B),
    rule = Color(0xFF2A3248),
    ruleStrong = Color(0xFF6D7790),
    ink = Color(0xFFF3F4F7),
    inkMuted = Color(0xFF98A1B8),
    inkFaint = Color(0xFF566079),
    action = Color(0xFF768DF5),
    onAction = Color(0xFF0B0F1C),
    focus = Color(0xFF768DF5),
    danger = Color(0xFFFB8083),
    caution = Color(0xFFF5AF20),
    ok = Color(0xFF6AD5B6),
    predicted = Color(0xFFED89D2),
    dangerFill = Color(0xFFAC001E),
    cautionFill = Color(0xFFF5AF20),
    okFill = Color(0xFF0A6355),
    infoFill = Color(0xFF3350D6),
    onDangerFill = Color(0xFFFFFFFF),
    onCautionFill = Color(0xFF0B0F1C),
    onOkFill = Color(0xFFFFFFFF),
    onInfoFill = Color(0xFFFFFFFF),
)

val FieldFsColors = FsColors(
    canvas = Color(0xFFFFFFFF),
    surface = Color(0xFFFFFFFF),
    rule = Color(0xFF98A1B8),
    ruleStrong = Color(0xFF0B0F1C),
    ink = Color(0xFF0B0F1C),
    inkMuted = Color(0xFF2A3248),
    inkFaint = Color(0xFF566079),
    action = Color(0xFF3350D6),
    onAction = Color(0xFFFFFFFF),
    focus = Color(0xFF3350D6),
    danger = Color(0xFFAC001E),
    caution = Color(0xFFB34F0C),
    ok = Color(0xFF0A6355),
    predicted = Color(0xFFA22488),
    dangerFill = Color(0xFFAC001E),
    cautionFill = Color(0xFFF5AF20),
    okFill = Color(0xFF0A6355),
    infoFill = Color(0xFF3350D6),
    onDangerFill = Color(0xFFFFFFFF),
    onCautionFill = Color(0xFF0B0F1C),
    onOkFill = Color(0xFFFFFFFF),
    onInfoFill = Color(0xFFFFFFFF),
)

val LocalFsColors = staticCompositionLocalOf { LightFsColors }

/** Material 3 roles mapped from the FusionSpace roles. Use with MaterialTheme(colorScheme = ...). */
val FsLightScheme = lightColorScheme(
    primary = Color(0xFF3350D6), onPrimary = Color(0xFFFFFFFF),
    background = Color(0xFFF3F4F7), onBackground = Color(0xFF0B0F1C),
    surface = Color(0xFFFFFFFF), onSurface = Color(0xFF0B0F1C), onSurfaceVariant = Color(0xFF566079),
    outline = Color(0xFF566079), outlineVariant = Color(0xFFD6DAE4),
    error = Color(0xFFAC001E),
)

val FsDarkScheme = darkColorScheme(
    primary = Color(0xFF768DF5), onPrimary = Color(0xFF0B0F1C),
    background = Color(0xFF0B0F1C), onBackground = Color(0xFFF3F4F7),
    surface = Color(0xFF141A2B), onSurface = Color(0xFFF3F4F7), onSurfaceVariant = Color(0xFF98A1B8),
    outline = Color(0xFF6D7790), outlineVariant = Color(0xFF2A3248),
    error = Color(0xFFFB8083),
)

const val FS_FIELD_TARGET_DP = 96  // controls used at the pad (about 15 mm)
const val FS_GLOVE_TARGET_DP = 128  // the one critical control used with gloves (about 20 mm)
