// FusionSpace product colours for SwiftUI. Generated by tools/build/kit_product.py; edit there, not here.
// FS.<role> follows the system: light, dark, and the field theme when Increase Contrast is on in light appearance.
// For a screen that must be in the field theme (countdown, arming, recovery), read FS.palette(for: .field, ...) or set
// .environment(\.fsTheme, .field) and use the palette from the environment (see FSPaletteReader below).
import SwiftUI
#if canImport(UIKit)
import UIKit
#endif

public enum FSTheme: Sendable { case system, light, dark, field }

public struct FSPalette: Sendable {
    public let canvas: Color
    public let surface: Color
    public let rule: Color
    public let ruleStrong: Color
    public let ink: Color
    public let inkMuted: Color
    public let inkFaint: Color
    public let action: Color
    public let onAction: Color
    public let focus: Color
    public let danger: Color
    public let caution: Color
    public let ok: Color
    public let predicted: Color
}

public enum FS {
    public static let lightPalette = FSPalette(canvas: Color(hex: 0xF3F4F7), surface: Color(hex: 0xFFFFFF), rule: Color(hex: 0xD6DAE4), ruleStrong: Color(hex: 0x566079), ink: Color(hex: 0x0B0F1C), inkMuted: Color(hex: 0x566079), inkFaint: Color(hex: 0x98A1B8), action: Color(hex: 0x3350D6), onAction: Color(hex: 0xFFFFFF), focus: Color(hex: 0x3350D6), danger: Color(hex: 0xAC001E), caution: Color(hex: 0xB34F0C), ok: Color(hex: 0x0A6355), predicted: Color(hex: 0xA22488))
    public static let darkPalette = FSPalette(canvas: Color(hex: 0x0B0F1C), surface: Color(hex: 0x141A2B), rule: Color(hex: 0x2A3248), ruleStrong: Color(hex: 0x6D7790), ink: Color(hex: 0xF3F4F7), inkMuted: Color(hex: 0x98A1B8), inkFaint: Color(hex: 0x566079), action: Color(hex: 0x768DF5), onAction: Color(hex: 0x0B0F1C), focus: Color(hex: 0x768DF5), danger: Color(hex: 0xFB8083), caution: Color(hex: 0xF5AF20), ok: Color(hex: 0x6AD5B6), predicted: Color(hex: 0xED89D2))
    public static let fieldPalette = FSPalette(canvas: Color(hex: 0xFFFFFF), surface: Color(hex: 0xFFFFFF), rule: Color(hex: 0x98A1B8), ruleStrong: Color(hex: 0x0B0F1C), ink: Color(hex: 0x0B0F1C), inkMuted: Color(hex: 0x2A3248), inkFaint: Color(hex: 0x566079), action: Color(hex: 0x3350D6), onAction: Color(hex: 0xFFFFFF), focus: Color(hex: 0x3350D6), danger: Color(hex: 0xAC001E), caution: Color(hex: 0xB34F0C), ok: Color(hex: 0x0A6355), predicted: Color(hex: 0xA22488))

    /// The palette for a theme; .system resolves from the colour scheme and contrast.
    public static func palette(for theme: FSTheme, scheme: ColorScheme, contrast: ColorSchemeContrast) -> FSPalette {
        switch theme {
        case .light: return lightPalette
        case .dark: return darkPalette
        case .field: return fieldPalette
        case .system: return scheme == .dark ? darkPalette : (contrast == .increased ? fieldPalette : lightPalette)
        }
    }

    // Semantic roles that follow the system (light, dark, field on Increase Contrast in light)
    /// Page and screen background
    public static let canvas = dynamic(light: 0xF3F4F7, dark: 0x0B0F1C, increasedContrast: 0xFFFFFF)
    /// Raised panels, inputs, tables, dialogs (separated by rules, never shadows)
    public static let surface = dynamic(light: 0xFFFFFF, dark: 0x141A2B, increasedContrast: 0xFFFFFF)
    /// Hairlines between rows, sections and cells (decoration: no contrast minimum)
    public static let rule = dynamic(light: 0xD6DAE4, dark: 0x2A3248, increasedContrast: 0x98A1B8)
    /// Control borders and chart axes (3:1 against canvas and surface)
    public static let ruleStrong = dynamic(light: 0x566079, dark: 0x6D7790, increasedContrast: 0x0B0F1C)
    /// Text, primary lines, measured data
    public static let ink = dynamic(light: 0x0B0F1C, dark: 0xF3F4F7, increasedContrast: 0x0B0F1C)
    /// Secondary text: labels, units, captions, sources
    public static let inkMuted = dynamic(light: 0x566079, dark: 0x98A1B8, increasedContrast: 0x2A3248)
    /// Disabled text and hatching (not for anything that must be read, placeholders included)
    public static let inkFaint = dynamic(light: 0x98A1B8, dark: 0x566079, increasedContrast: 0x566079)
    /// Links, selection, focus, the one interactive accent
    public static let action = dynamic(light: 0x3350D6, dark: 0x768DF5, increasedContrast: 0x3350D6)
    /// Text on an action fill
    public static let onAction = dynamic(light: 0xFFFFFF, dark: 0x0B0F1C, increasedContrast: 0xFFFFFF)
    /// Focus ring (2 px outline, 2 px offset)
    public static let focus = dynamic(light: 0x3350D6, dark: 0x768DF5, increasedContrast: 0x3350D6)
    /// Danger ink: text, icons and lines
    public static let danger = dynamic(light: 0xAC001E, dark: 0xFB8083, increasedContrast: 0xAC001E)
    /// Caution ink: text, icons and lines
    public static let caution = dynamic(light: 0xB34F0C, dark: 0xF5AF20, increasedContrast: 0xB34F0C)
    /// Normal ink: text, icons and lines
    public static let ok = dynamic(light: 0x0A6355, dark: 0x6AD5B6, increasedContrast: 0x0A6355)
    /// Predicted, simulated or forecast data (always dashed or hatched too)
    public static let predicted = dynamic(light: 0xA22488, dark: 0xED89D2, increasedContrast: 0xA22488)
    // Signal fills: the same on every background, like a safety sign
    public static let dangerFill = Color(hex: 0xAC001E)
    public static let onDangerFill = Color(hex: 0xFFFFFF)
    public static let cautionFill = Color(hex: 0xF5AF20)
    public static let onCautionFill = Color(hex: 0x0B0F1C)
    public static let okFill = Color(hex: 0x0A6355)
    public static let onOkFill = Color(hex: 0xFFFFFF)
    public static let infoFill = Color(hex: 0x3350D6)
    public static let onInfoFill = Color(hex: 0xFFFFFF)
    /// Identity only, always leading to trailing. Never a status or a data scale.
    public static let gradient = LinearGradient(colors: [Color(hex: 0xDA7C30), Color(hex: 0xD07D7A), Color(hex: 0xA188CB), Color(hex: 0x768DF5)], startPoint: .leading, endPoint: .trailing)

    // Type: Cascadia Mono for titles, section heads, labels, readouts and codes; Archivo for prose in content; controls and
    // list text stay in the system font. All scale with Dynamic Type.
    public static func title() -> Font { .custom("CascadiaMono-SemiBold", size: 28, relativeTo: .title) }
    public static func heading() -> Font { .custom("CascadiaMono-SemiBold", size: 14, relativeTo: .headline) }   // with .textCase(.uppercase)
    public static func label() -> Font { .custom("CascadiaMono-Regular", size: 12, relativeTo: .caption) }      // with .textCase(.uppercase)
    public static func readout(_ size: CGFloat = 28, relativeTo style: Font.TextStyle = .title) -> Font { .custom("CascadiaMono-Regular", size: size, relativeTo: style).monospacedDigit() }
    public static func prose() -> Font { .custom("Archivo-Regular", size: 17, relativeTo: .body) }

    public static let fieldTarget: CGFloat = 96   // pt, controls used at the pad (about 15 mm)
    public static let gloveTarget: CGFloat = 128   // pt, the one critical control used with gloves (about 20 mm)

    static func dynamic(light: UInt32, dark: UInt32, increasedContrast: UInt32) -> Color {
        #if canImport(UIKit)
        return Color(UIColor { t in
            if t.userInterfaceStyle == .dark { return UIColor(hex: dark) }
            return UIColor(hex: t.accessibilityContrast == .high ? increasedContrast : light)
        })
        #else
        return Color(hex: light)
        #endif
    }
}

private struct FSThemeKey: EnvironmentKey { static let defaultValue: FSTheme = .system }
extension EnvironmentValues {
    /// The FusionSpace theme for this part of the view tree (.system unless a screen forces .field).
    public var fsTheme: FSTheme {
        get { self[FSThemeKey.self] }
        set { self[FSThemeKey.self] = newValue }
    }
}

/// Hands its content the palette for the current theme, colour scheme and contrast.
public struct FSPaletteReader<Content: View>: View {
    @Environment(\.fsTheme) private var theme
    @Environment(\.colorScheme) private var scheme
    @Environment(\.colorSchemeContrast) private var contrast
    private let content: (FSPalette) -> Content
    public init(@ViewBuilder content: @escaping (FSPalette) -> Content) { self.content = content }
    public var body: some View { content(FS.palette(for: theme, scheme: scheme, contrast: contrast)) }
}

extension Color {
    init(hex: UInt32) { self.init(.sRGB, red: Double((hex >> 16) & 0xFF) / 255, green: Double((hex >> 8) & 0xFF) / 255, blue: Double(hex & 0xFF) / 255) }
}
#if canImport(UIKit)
extension UIColor {
    convenience init(hex: UInt32) { self.init(red: CGFloat((hex >> 16) & 0xFF) / 255, green: CGFloat((hex >> 8) & 0xFF) / 255, blue: CGFloat(hex & 0xFF) / 255, alpha: 1) }
}
#endif
