// SPDX-License-Identifier: Apache-2.0 · Copyright 2026 Neer Patel
// FusionSpace content-layer parts for Jetpack Compose (and Compose Multiplatform). Generated by tools/build/kit_mobile.py
// from source/product/mobile/; edit there. Needs FusionSpaceColors.kt (product/tokens/).
//
// These are the parts FusionSpace owns (product/mobile.md): the theme wrapper, readouts, status chips, sheet headers, the
// title block, the held confirmation for arming, and commanded-vs-confirmed state. Bars, lists, switches and pickers stay
// Material 3's, themed through FsLightScheme / FsDarkScheme.
package co.fusionspace.design

import androidx.compose.animation.core.Animatable
import androidx.compose.animation.core.LinearEasing
import androidx.compose.animation.core.tween
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.gestures.awaitEachGesture
import androidx.compose.foundation.gestures.awaitFirstDown
import androidx.compose.foundation.gestures.waitForUpOrCancellation
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.heightIn
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.layout.widthIn
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.ColorScheme
import androidx.compose.material3.LocalContentColor
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.Typography
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.drawBehind
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.Outline
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.Shape
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathEffect
import androidx.compose.ui.graphics.lerp
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.hapticfeedback.HapticFeedbackType
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.layout.IntrinsicMeasurable
import androidx.compose.ui.layout.IntrinsicMeasureScope
import androidx.compose.ui.layout.Layout
import androidx.compose.ui.layout.Measurable
import androidx.compose.ui.layout.MeasurePolicy
import androidx.compose.ui.layout.MeasureResult
import androidx.compose.ui.layout.MeasureScope
import androidx.compose.ui.platform.LocalHapticFeedback
import androidx.compose.ui.semantics.CustomAccessibilityAction
import androidx.compose.ui.semantics.Role
import androidx.compose.ui.semantics.clearAndSetSemantics
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.customActions
import androidx.compose.ui.semantics.heading
import androidx.compose.ui.semantics.role
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.semantics.stateDescription
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.Constraints
import androidx.compose.ui.unit.Density
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.LayoutDirection
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.em
import androidx.compose.ui.unit.sp
import kotlinx.coroutines.launch

// ------------------------------------------------------------------ theme

/** Which FusionSpace palette a part of the tree uses. Field is the outdoor theme: countdown, arming and recovery. */
enum class FsTheme { System, Light, Dark, Field }

/**
 * The FusionSpace theme: the static brand scheme for Material 3 (never dynamic color for anything that carries meaning),
 * the FusionSpace roles in [LocalFsColors], and type with Cascadia Mono for titles and labels. Pass the bundled fonts:
 * on Android, `FontFamily(Font(R.font.cascadia_mono_semibold, FontWeight.SemiBold), Font(R.font.cascadia_mono_regular))`.
 * Body and list text stay in the system font (Roboto), so they scale and read like the rest of the phone.
 */
@Composable
fun FusionSpaceTheme(
    theme: FsTheme = FsTheme.System,
    highContrast: Boolean = false,          // the system's high-contrast setting turns the field theme on in light
    mono: FontFamily = FontFamily.Monospace,
    content: @Composable () -> Unit,
) {
    val dark = when (theme) { FsTheme.Dark -> true; FsTheme.System -> isSystemInDarkTheme(); else -> false }
    val colors = when {
        theme == FsTheme.Field -> FieldFsColors
        dark -> DarkFsColors
        theme == FsTheme.System && highContrast -> FieldFsColors
        else -> LightFsColors
    }
    val base = Typography()
    val display = { s: TextStyle -> s.copy(fontFamily = mono, fontWeight = FontWeight.SemiBold) }
    val typography = base.copy(
        displaySmall = display(base.displaySmall), headlineMedium = display(base.headlineMedium),
        headlineSmall = display(base.headlineSmall), titleLarge = display(base.titleLarge),
    )
    CompositionLocalProvider(LocalFsColors provides colors, LocalFsMono provides mono) {
        MaterialTheme(colorScheme = fsScheme(if (dark) FsDarkScheme else FsLightScheme, colors), typography = typography, content = content)
    }
}

/**
 * The Material roles FsLightScheme / FsDarkScheme leave at Material's baseline (purple) defaults, filled from the FusionSpace
 * roles: dialogs, menus, sheets and app bars use the surface containers, and the field theme's whiter canvas and darker
 * muted ink reach the Material components too.
 */
private fun fsScheme(base: ColorScheme, c: FsColors): ColorScheme {
    val tinted = lerp(c.surface, c.action, 0.16f)
    return base.copy(
        background = c.canvas, onBackground = c.ink, surface = c.surface, onSurface = c.ink,
        surfaceVariant = c.surface, onSurfaceVariant = c.inkMuted, outline = c.ruleStrong, outlineVariant = c.rule,
        surfaceTint = c.action, surfaceBright = c.surface, surfaceDim = c.canvas,
        surfaceContainerLowest = c.surface, surfaceContainerLow = c.surface, surfaceContainer = c.surface,
        surfaceContainerHigh = c.surface, surfaceContainerHighest = c.surface,
        primary = c.action, onPrimary = c.onAction, primaryContainer = tinted, onPrimaryContainer = c.ink,
        secondary = c.inkMuted, onSecondary = c.surface, secondaryContainer = tinted, onSecondaryContainer = c.ink,
        tertiary = c.predicted, onTertiary = c.surface, tertiaryContainer = c.surface, onTertiaryContainer = c.predicted,
        inverseSurface = c.ink, inverseOnSurface = c.canvas, inversePrimary = c.action, scrim = Color.Black,
    )
}

val LocalFsMono = androidx.compose.runtime.staticCompositionLocalOf<FontFamily> { FontFamily.Monospace }

private object FsType {
    @Composable fun label() = TextStyle(fontFamily = LocalFsMono.current, fontSize = 12.sp, lineHeight = 16.sp, letterSpacing = 0.06.em)
    @Composable fun heading() = TextStyle(fontFamily = LocalFsMono.current, fontWeight = FontWeight.SemiBold, fontSize = 14.sp, lineHeight = 20.sp, letterSpacing = 0.04.em)
    @Composable fun readout(size: Int) = TextStyle(fontFamily = LocalFsMono.current, fontSize = size.sp, lineHeight = (size + 4).sp, fontFeatureSettings = "tnum, zero")
}

// ------------------------------------------------------------------ signals

/** A state with a word and a shape. Color is the third cue, never the only one. */
enum class FsSignal { Danger, Caution, Ok, Info, Off, Stale, Predicted }

/**
 * A status chip: `CONT`, `ARMED`, `NOT USED`. Danger, caution and normal are filled the same on every background, like a
 * safety sign; the others are outlined. [icon] is a FusionSpace icon (product/icons/android/) drawn by the caller; an
 * `Icon` there takes the chip's foreground color through LocalContentColor. The word is set in capitals; [detail] (a value
 * with its unit joined by a non-breaking space, "0.3\u00A0s") follows it as written, since a capital S is siemens, not seconds.
 */
@Composable
fun FsStatus(word: String, signal: FsSignal, modifier: Modifier = Modifier, detail: String? = null, icon: (@Composable () -> Unit)? = null) {
    val c = LocalFsColors.current
    val (fg, bg) = when (signal) {
        FsSignal.Danger -> c.onDangerFill to c.dangerFill
        FsSignal.Caution -> c.onCautionFill to c.cautionFill
        FsSignal.Ok -> c.onOkFill to c.okFill
        FsSignal.Info -> c.action to Color.Transparent
        FsSignal.Off -> c.inkMuted to Color.Transparent
        FsSignal.Stale -> c.inkMuted to c.surface
        FsSignal.Predicted -> c.predicted to Color.Transparent
    }
    val edge = when (signal) {
        FsSignal.Info -> Modifier.border(1.dp, c.action)
        FsSignal.Off, FsSignal.Stale -> Modifier.border(1.dp, c.ruleStrong)
        FsSignal.Predicted -> Modifier.dashedBorder(c.predicted)
        else -> Modifier
    }
    Row(
        modifier.background(bg).then(edge).heightIn(min = 24.dp).padding(horizontal = 8.dp)
            .clearAndSetSemantics { contentDescription = listOfNotNull(word, detail).joinToString(", ") },
        verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(6.dp),
    ) {
        if (signal == FsSignal.Stale) FsHatch(c.inkFaint, Modifier.width(8.dp).height(24.dp))
        icon?.let { CompositionLocalProvider(LocalContentColor provides fg, content = it) }
        // The word is never split ("CO / NT"): it stays on one line. The detail keeps its whole width on the same line
        // whenever the chip has room; only when it doesn't (very large text) does the detail wrap and the chip grow taller.
        // Lay chips out in a FlowRow, so a large text size moves a chip to the next line first.
        val style = FsType.label().copy(fontWeight = FontWeight.SemiBold)
        FsFirstThatFits {
            Text(word.uppercase() + (detail?.let { " · $it" } ?: ""), style = style, color = fg, maxLines = 1, softWrap = false)
            Row(Modifier.padding(vertical = 4.dp)) {
                Text(word.uppercase(), style = style, color = fg, maxLines = 1, softWrap = false)
                detail?.let { Text(" · $it", style = style, color = fg, modifier = Modifier.weight(1f, fill = false)) }
            }
        }
    }
}

private fun Modifier.dashedBorder(color: Color) = this.drawBehind {
    drawRect(color, style = Stroke(width = 1.dp.toPx(), pathEffect = PathEffect.dashPathEffect(floatArrayOf(4.dp.toPx(), 2.dp.toPx()))))
}

/** 45° hatching, 1 dp lines every 6 dp: unavailable, stale or out of range (an ISO 128 section line). */
@Composable
fun FsHatch(color: Color, modifier: Modifier = Modifier) {
    Canvas(modifier) {
        val step = 6.dp.toPx()
        var x = -size.height
        while (x < size.width) {
            drawLine(color, Offset(x, size.height), Offset(x + size.height, 0f), strokeWidth = 1.dp.toPx())
            x += step
        }
    }
}

// ------------------------------------------------------------------ readouts

enum class FsReadoutKind { Measured, Predicted, Stale }

/**
 * A number someone came for: a label, the value with its unit, and a qualifier that says where it came from or how far to
 * trust it. Predicted values carry a dashed underline (drawn); stale ones turn muted with a hatched block.
 * [spokenUnit] is the unit as TalkBack should say it ("feet above ground level" for "ft AGL").
 */
@Composable
fun FsReadout(
    label: String, value: String, unit: String, modifier: Modifier = Modifier, qualifier: String? = null,
    kind: FsReadoutKind = FsReadoutKind.Measured, size: Int = {{READOUT}}, spokenUnit: String? = null,
) {
    val c = LocalFsColors.current
    val spoken = buildString {
        if (kind == FsReadoutKind.Predicted) append("predicted, ")
        append("$value ${spokenUnit ?: unit}")
        if (kind == FsReadoutKind.Stale) append(", stale")
        qualifier?.let { append(", $it") }
    }
    val full = FsType.readout(size)
    // The number never breaks across lines: it has one line at its size, or a little smaller, beside its unit; when even
    // that doesn't fit (very large text in a narrow column), the unit goes under it, and only then does it shrink further.
    val number = @Composable { scale: Float ->
        Text(
            value, style = full.copy(fontSize = full.fontSize * scale, lineHeight = full.lineHeight * scale),
            color = if (kind == FsReadoutKind.Stale) c.inkMuted else c.ink, maxLines = 1, softWrap = false,
            modifier = if (kind == FsReadoutKind.Predicted) Modifier.predictedUnderline(c.predicted) else Modifier,
        )
    }
    val stale = @Composable { if (kind == FsReadoutKind.Stale) FsHatch(c.inkFaint, Modifier.width(10.dp).height(size.dp).border(1.dp, c.ruleStrong)) }
    val unitText = @Composable { Text(unit, style = FsType.label().copy(letterSpacing = 0.em), color = c.inkMuted, modifier = Modifier.padding(bottom = 4.dp)) }
    Column(modifier.clearAndSetSemantics { contentDescription = "$label, $spoken" }, verticalArrangement = Arrangement.spacedBy(4.dp)) {
        Text(label.uppercase(), style = FsType.label(), color = c.inkMuted)
        FsFirstThatFits {
            Row(verticalAlignment = Alignment.Bottom, horizontalArrangement = Arrangement.spacedBy(6.dp)) { stale(); number(1f); unitText() }
            Row(verticalAlignment = Alignment.Bottom, horizontalArrangement = Arrangement.spacedBy(6.dp)) { stale(); number(0.85f); unitText() }
            Column {
                Row(verticalAlignment = Alignment.Bottom, horizontalArrangement = Arrangement.spacedBy(6.dp)) {
                    stale()
                    FsFirstThatFits { number(1f); number(0.85f); number(0.7f); number(0.6f) }
                }
                unitText()
            }
        }
        qualifier?.let { Text(it, style = MaterialTheme.typography.bodySmall, color = c.inkMuted) }
    }
}

private fun Modifier.predictedUnderline(color: Color) = this.drawBehind {
    val y = size.height - 1.dp.toPx()
    drawLine(color, Offset(0f, y), Offset(size.width, y), strokeWidth = 2.dp.toPx(),
        pathEffect = PathEffect.dashPathEffect(floatArrayOf(8.dp.toPx(), 4.dp.toPx())))
}

// ------------------------------------------------------------------ sheets and the title block

/** The top of a section: a 2 dp rule (the sheet's edge), its name, and `SHEET n / N`. */
@Composable
fun FsSheetHeader(name: String, number: Int, total: Int, modifier: Modifier = Modifier) {
    val c = LocalFsColors.current
    Column(modifier.fillMaxWidth(), verticalArrangement = Arrangement.spacedBy(8.dp)) {
        Box(Modifier.fillMaxWidth().height(2.dp).background(c.ink))
        val title = @Composable { Text(name.uppercase(), style = FsType.heading(), color = c.ink, modifier = Modifier.semantics { heading() }) }
        val sheet = @Composable {
            Text("SHEET $number / $total", style = FsType.label(), color = c.inkMuted, maxLines = 1, softWrap = false,
                modifier = Modifier.clearAndSetSemantics { contentDescription = "Sheet $number of $total" })
        }
        // The name and the sheet number on one line, or the number under the name when the text is too large for both.
        FsFirstThatFits {
            Row(Modifier.fillMaxWidth(), verticalAlignment = Alignment.Bottom) { title(); Spacer(Modifier.width(12.dp)); Spacer(Modifier.weight(1f)); sheet() }
            Column(verticalArrangement = Arrangement.spacedBy(2.dp)) { title(); sheet() }
        }
    }
}

/** One cell of the title block; a wide cell takes a row to itself. */
data class FsTitleCell(val key: String, val value: String, val wide: Boolean = false)

/** The About screen as a drawing's title block: owner, title, designation, revision, versions, data, licenses. */
@Composable
fun FsTitleBlock(cells: List<FsTitleCell>, modifier: Modifier = Modifier, mark: (@Composable () -> Unit)? = null) {
    val c = LocalFsColors.current
    val rows = buildList {
        var cur = mutableListOf<FsTitleCell>()
        for (cell in cells) {
            if (cell.wide) { if (cur.isNotEmpty()) { add(cur); cur = mutableListOf() }; add(listOf(cell)) }
            else { cur.add(cell); if (cur.size == 2) { add(cur); cur = mutableListOf() } }
        }
        if (cur.isNotEmpty()) add(cur)
    }
    Column(modifier.fillMaxWidth().background(c.surface).border(2.dp, c.ink)) {
        for (row in rows) {
            Row(Modifier.fillMaxWidth()) {
                for (cell in row) {
                    Column(
                        Modifier.weight(1f).border(0.5.dp, c.ruleStrong).padding(horizontal = 10.dp, vertical = 6.dp)
                            .semantics(mergeDescendants = true) {},
                        verticalArrangement = Arrangement.spacedBy(2.dp),
                    ) {
                        Text(cell.key.uppercase(), style = FsType.label().copy(fontSize = 11.sp, letterSpacing = 0.08.em), color = c.inkMuted)
                        Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                            if (cell.key == "Owner") mark?.invoke()
                            Text(cell.value, style = FsType.readout(14), color = c.ink)
                        }
                    }
                }
                if (row.size == 1 && !row[0].wide) Spacer(Modifier.weight(1f))
            }
        }
    }
}

// ------------------------------------------------------------------ device state

/** What the app asked the hardware to do, and what the hardware says it is. The app never assumes. */
@Composable
fun FsCommandedConfirmed(commanded: String?, confirmed: String, age: String, modifier: Modifier = Modifier) {
    val c = LocalFsColors.current
    val label = @Composable { text: String, m: Modifier -> Text(text, style = FsType.label(), color = c.inkMuted, modifier = m, maxLines = 1, softWrap = false) }
    val value = @Composable { text: String -> Text(text, style = FsType.readout(15), color = c.ink) }
    // Each label beside its value while both fit on a line; with larger text, each label above its value, so no word breaks.
    FsFirstThatFits(modifier.clearAndSetSemantics { contentDescription = "Commanded ${commanded ?: "nothing"}. Confirmed $confirmed, $age." }) {
        Column(verticalArrangement = Arrangement.spacedBy(4.dp)) {
            val beside = Modifier.widthIn(min = 104.dp).padding(end = 8.dp)
            Row { label("COMMANDED", beside); value(commanded ?: "—") }
            Row { label("CONFIRMED", beside); value("$confirmed · $age") }
        }
        Column(verticalArrangement = Arrangement.spacedBy(2.dp)) {
            label("COMMANDED", Modifier); value(commanded ?: "—")
            label("CONFIRMED", Modifier.padding(top = 4.dp)); value("$confirmed · $age")
        }
    }
}

/**
 * A designation tag: a mono label in a 1 dp box with its top-right corner cut at 45° (`FS-VEGA-004 rev B`), like a
 * drawing's tag. It wraps at very large text sizes rather than truncating.
 */
@Composable
fun FsTag(text: String, modifier: Modifier = Modifier) {
    val c = LocalFsColors.current
    Text(
        text, style = TextStyle(fontFamily = LocalFsMono.current, fontSize = 12.sp, lineHeight = 16.sp), color = c.ink,
        modifier = modifier.border(1.dp, c.ruleStrong, FsChamfer(4.dp)).padding(start = 8.dp, end = 10.dp, top = 3.dp, bottom = 3.dp),
    )
}

/** A rectangle with its top-right corner cut at 45° by [cut] (tags, sheet corners). */
class FsChamfer(private val cut: Dp) : Shape {
    override fun createOutline(size: Size, layoutDirection: LayoutDirection, density: Density): Outline {
        val k = with(density) { cut.toPx() }.coerceAtMost(minOf(size.width, size.height))
        return Outline.Generic(Path().apply {
            moveTo(0f, 0f); lineTo(size.width - k, 0f); lineTo(size.width, k); lineTo(size.width, size.height); lineTo(0f, size.height); close()
        })
    }
}

/** The flight's phases, in order (product/mobile.md#screens). */
val FsPhases = listOf("PAD", "BOOST", "COAST", "APOGEE", "DROGUE", "MAIN", "LANDED")

/**
 * The flight's phases: done in ink, now inverted, next muted (inkFaint is for disabled text; these must be read). When
 * the seven names don't fit (a narrow screen, large text), it shows the current phase in words with its place,
 * "MAIN · 6 of 7", and a tick per phase, rather than abbreviating the names. [current] is an index into [FsPhases].
 */
@Composable
fun FsPhaseStrip(current: Int, modifier: Modifier = Modifier) {
    val c = LocalFsColors.current
    val mono = LocalFsMono.current
    FsFirstThatFits(modifier.fillMaxWidth().clearAndSetSemantics {
        contentDescription = "Phase: ${FsPhases[current].lowercase()}, ${current + 1} of ${FsPhases.size}"
    }) {
        Layout(
            content = {
                FsPhases.forEachIndexed { i, name ->
                    Box(Modifier.background(if (i == current) c.ink else Color.Transparent), contentAlignment = Alignment.Center) {
                        Text(
                            name, maxLines = 1, softWrap = false, textAlign = TextAlign.Center,
                            style = TextStyle(fontFamily = mono, fontSize = 10.sp, lineHeight = 14.sp, letterSpacing = 0.04.em,
                                fontWeight = if (i == current) FontWeight.SemiBold else FontWeight.Normal),
                            color = when { i < current -> c.ink; i == current -> c.canvas; else -> c.inkMuted },
                            modifier = Modifier.padding(horizontal = 3.dp, vertical = 6.dp),
                        )
                    }
                }
            },
            modifier = Modifier.fillMaxWidth().border(1.dp, c.ruleStrong),
            measurePolicy = EqualCells,
        )
        Column(Modifier.fillMaxWidth(), verticalArrangement = Arrangement.spacedBy(6.dp)) {
            Text("${FsPhases[current]} · ${current + 1} of ${FsPhases.size}", color = c.ink,
                style = TextStyle(fontFamily = mono, fontSize = 12.sp, lineHeight = 16.sp, fontWeight = FontWeight.SemiBold))
            Row(Modifier.fillMaxWidth().height(10.dp), horizontalArrangement = Arrangement.spacedBy(3.dp), verticalAlignment = Alignment.CenterVertically) {
                FsPhases.indices.forEach { i ->
                    Box(Modifier.weight(1f).height(if (i == current) 10.dp else 6.dp).background(if (i <= current) c.ink else Color.Transparent)
                        .border(1.dp, if (i <= current) c.ink else c.ruleStrong))
                }
            }
        }
    }
}

/** Cells of one width (the widest one's), filling the width they're given; as wide as all of them at their own size otherwise. */
private object EqualCells : MeasurePolicy {
    override fun MeasureScope.measure(measurables: List<Measurable>, constraints: Constraints): MeasureResult {
        val n = measurables.size
        val natural = measurables.maxOf { it.maxIntrinsicWidth(Constraints.Infinity) }
        val total = if (constraints.hasBoundedWidth) constraints.maxWidth else natural * n
        val widths = List(n) { i -> total / n + if (i < total % n) 1 else 0 }
        val h = maxOf(constraints.minHeight, measurables.indices.maxOf { measurables[it].minIntrinsicHeight(widths[it]) })
        val placeables = measurables.mapIndexed { i, m -> m.measure(Constraints.fixed(widths[i], h)) }
        return layout(total, h) { var x = 0; placeables.forEach { it.place(x, 0); x += it.width } }
    }
    override fun IntrinsicMeasureScope.maxIntrinsicWidth(measurables: List<IntrinsicMeasurable>, height: Int) =
        measurables.maxOf { it.maxIntrinsicWidth(height) } * measurables.size
    override fun IntrinsicMeasureScope.minIntrinsicWidth(measurables: List<IntrinsicMeasurable>, height: Int) =
        maxIntrinsicWidth(measurables, height)
    override fun IntrinsicMeasureScope.minIntrinsicHeight(measurables: List<IntrinsicMeasurable>, width: Int) =
        measurables.maxOf { it.minIntrinsicHeight(width / measurables.size) }
    override fun IntrinsicMeasureScope.maxIntrinsicHeight(measurables: List<IntrinsicMeasurable>, width: Int) =
        minIntrinsicHeight(measurables, width)
}

/**
 * The first of its children that fits the width it's given at its own size, every text on one line (like SwiftUI's
 * ViewThatFits): put the one-line arrangement first and the stacked one last. The last child is the fallback and gets
 * the width as it is, so its texts may wrap, at spaces. Children that aren't chosen are neither measured nor drawn.
 */
@Composable
fun FsFirstThatFits(modifier: Modifier = Modifier, content: @Composable () -> Unit) {
    Layout(content, modifier) { measurables, constraints ->
        val chosen = measurables.dropLast(1).firstOrNull {
            !constraints.hasBoundedWidth || it.maxIntrinsicWidth(Constraints.Infinity) <= constraints.maxWidth
        } ?: measurables.last()
        val p = chosen.measure(constraints)
        layout(p.width, p.height) { p.place(0, 0) }
    }
}

/**
 * The device's state as a box: SAFE outlined, ARMED inverted (product/embedded.md). Nothing else uses the inverted box.
 * TalkBack hears "Device state: SAFE", not a bare "SAFE" that would sound like the SAFE button beside it.
 */
@Composable
fun FsStateBox(armed: Boolean, modifier: Modifier = Modifier) {
    val c = LocalFsColors.current
    val word = if (armed) "ARMED" else "SAFE"
    Text(
        word, style = FsType.readout(28).copy(fontWeight = FontWeight.SemiBold),
        color = if (armed) c.onDangerFill else c.ink,
        modifier = modifier.clearAndSetSemantics { contentDescription = "Device state: $word" }.background(if (armed) c.dangerFill else Color.Transparent)
            .border(3.dp, if (armed) c.dangerFill else c.ink).padding(horizontal = 14.dp, vertical = 10.dp),
    )
}

// ------------------------------------------------------------------ held confirmation (arming)

/**
 * Arming from the app is a second step on top of the airframe's switch: a press held for {{HOLD_S}} s that shows the device's
 * designation (product/embedded.md). Letting go early cancels. TalkBack and Switch Access get the accessible alternative,
 * still two steps: a custom action that opens [FsArmConfirmation]; show the same as a visible text button under it ("Arm
 * with a confirmation instead"). Put SAFE, one action, to its right.
 */
@Composable
fun FsHoldToConfirm(
    title: String, designation: String, onConfirmed: () -> Unit, modifier: Modifier = Modifier, holdMillis: Int = {{HOLD_MS}},
    action: String = title.removePrefix("Hold to ").replaceFirstChar { it.uppercase() },
) {
    val c = LocalFsColors.current
    val haptics = LocalHapticFeedback.current
    val scope = rememberCoroutineScope()
    val progress = remember { Animatable(0f) }
    var confirming by remember { mutableStateOf(false) }
    Box(
        modifier
            .fillMaxWidth().heightIn(min = FS_GLOVE_TARGET_DP.dp)
            .background(c.surface)
            .drawBehind {
                // Drawn, not laid out: fill-height children would make the box take every bit of height it's offered.
                val bar = 8.dp.toPx(); val done = size.width * progress.value
                drawRect(c.danger.copy(alpha = 0.10f), size = Size(done, size.height))
                drawRect(c.rule, Offset(0f, size.height - bar), Size(size.width, bar))
                drawRect(c.danger, Offset(0f, size.height - bar), Size(done, bar))
            }
            .border(2.dp, c.ink)
            .pointerInput(holdMillis) {
                awaitEachGesture {
                    awaitFirstDown()
                    val run = scope.launch {
                        progress.animateTo(1f, tween(holdMillis, easing = LinearEasing))
                        haptics.performHapticFeedback(HapticFeedbackType.LongPress)
                        onConfirmed()
                    }
                    waitForUpOrCancellation()
                    run.cancel()
                    scope.launch { progress.animateTo(0f, tween(160)) }
                }
            }
            .semantics(mergeDescendants = true) {
                role = Role.Button
                contentDescription = "$title $designation. Press and hold for ${holdMillis / 1000} seconds."
                stateDescription = if (progress.value > 0f) "Holding" else ""
                customActions = listOf(CustomAccessibilityAction("$action with a confirmation") { confirming = true; true })
            },
    ) {
        // Clear of the 8 dp progress bar at the bottom, however large the text gets.
        Column(Modifier.align(Alignment.CenterStart).padding(start = 16.dp, end = 16.dp, top = 16.dp, bottom = 24.dp), verticalArrangement = Arrangement.spacedBy(6.dp)) {
            Text(title.uppercase(), style = FsType.heading().copy(fontSize = 18.sp), color = c.ink)
            Text("$designation · ${holdMillis / 1000}\u00A0s", style = FsType.readout(14), color = c.ink)
            if (progress.value > 0f) Text("Keep holding", style = FsType.label().copy(fontWeight = FontWeight.SemiBold), color = c.danger)
        }
    }
    if (confirming) FsArmConfirmation(action, designation, onConfirmed = { confirming = false; onConfirmed() }, onDismiss = { confirming = false })
}

/**
 * The accessible alternative to [FsHoldToConfirm], still two steps: a visible button ("Arm with a confirmation instead") or
 * the TalkBack action opens this, and the second step is its confirm button. [action] is the verb ("Arm"), not the hold
 * control's title.
 */
@Composable
fun FsArmConfirmation(action: String, designation: String, onConfirmed: () -> Unit, onDismiss: () -> Unit) {
    val c = LocalFsColors.current
    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text("$action $designation?") },
        text = { Text("The airframe's switch must already be on. SAFE stays one tap away.") },
        confirmButton = { TextButton(onClick = onConfirmed) { Text(action, color = c.danger) } },
        dismissButton = { TextButton(onClick = onDismiss) { Text("Cancel") } },
    )
}

// ------------------------------------------------------------------ freshness

/**
 * How old a value may get before it shows as stale (product/data.md#live-telemetry), and the age every live value carries.
 * The number and its unit are joined by a non-breaking space ("0.3\u00A0s ago"), so a line never breaks between them; do
 * the same wherever a value and its unit are written into one string.
 */
object FsFreshness {
    const val FLIGHT_MS = {{STALE_FLIGHT_MS}}L
    const val WEATHER_MS = {{STALE_WEATHER_MS}}L
    fun isStale(ageMs: Long, limitMs: Long) = ageMs > limitMs
    fun age(ageMs: Long): String {
        val s = ageMs.coerceAtLeast(0) / 1000.0
        return when {
            s < 10 -> "${"%.1f".format(s)}\u00A0s ago"
            s < 60 -> "${s.toInt()}\u00A0s ago"
            s < 3600 -> "${(s / 60).toInt()}\u00A0min ago"
            else -> "${(s / 3600).toInt()}\u00A0h ago"
        }
    }
}

/** Field-size target: {{FIELD}} dp for controls used at the pad (about 15 mm). Keep the screen on with Modifier.keepScreenOn(). */
fun Modifier.fsFieldTarget() = this.heightIn(min = FS_FIELD_TARGET_DP.dp)
