// SPDX-License-Identifier: Apache-2.0 · Copyright 2026 Neer Patel
// FusionSpace content-layer parts for Jetpack Compose (and Compose Multiplatform). Generated by tools/build/kit_mobile.py
// from source/product/mobile/; edit there. Needs FusionSpaceColors.kt (product/tokens/).
//
// These are the parts FusionSpace owns (product/mobile.md): the theme wrapper, readouts, status chips, sheet headers, the
// title block, the held confirmation for arming, and commanded-vs-confirmed state. Bars, lists, switches and pickers stay
// Material 3's, themed through FsLightScheme / FsDarkScheme.
package co.fusionspace.design

import androidx.compose.animation.core.Animatable
import androidx.compose.animation.core.LinearEasing
import androidx.compose.animation.core.tween
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.gestures.awaitEachGesture
import androidx.compose.foundation.gestures.awaitFirstDown
import androidx.compose.foundation.gestures.waitForUpOrCancellation
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxHeight
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.heightIn
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.Typography
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.drawBehind
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathEffect
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.hapticfeedback.HapticFeedbackType
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.platform.LocalHapticFeedback
import androidx.compose.ui.semantics.CustomAccessibilityAction
import androidx.compose.ui.semantics.Role
import androidx.compose.ui.semantics.clearAndSetSemantics
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.customActions
import androidx.compose.ui.semantics.heading
import androidx.compose.ui.semantics.role
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.semantics.stateDescription
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextDecoration
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.em
import androidx.compose.ui.unit.sp
import kotlinx.coroutines.launch

// ------------------------------------------------------------------ theme

/** Which FusionSpace palette a part of the tree uses. Field is the outdoor theme: countdown, arming and recovery. */
enum class FsTheme { System, Light, Dark, Field }

/**
 * The FusionSpace theme: the static brand scheme for Material 3 (never dynamic color for anything that carries meaning),
 * the FusionSpace roles in [LocalFsColors], and type with Cascadia Mono for titles and labels. Pass the bundled fonts:
 * on Android, `FontFamily(Font(R.font.cascadia_mono_semibold, FontWeight.SemiBold), Font(R.font.cascadia_mono_regular))`.
 * Body and list text stay in the system font (Roboto), so they scale and read like the rest of the phone.
 */
@Composable
fun FusionSpaceTheme(
    theme: FsTheme = FsTheme.System,
    highContrast: Boolean = false,          // the system's high-contrast setting turns the field theme on in light
    mono: FontFamily = FontFamily.Monospace,
    content: @Composable () -> Unit,
) {
    val dark = when (theme) { FsTheme.Dark -> true; FsTheme.System -> isSystemInDarkTheme(); else -> false }
    val colors = when {
        theme == FsTheme.Field -> FieldFsColors
        dark -> DarkFsColors
        theme == FsTheme.System && highContrast -> FieldFsColors
        else -> LightFsColors
    }
    val base = Typography()
    val display = { s: TextStyle -> s.copy(fontFamily = mono, fontWeight = FontWeight.SemiBold) }
    val typography = base.copy(
        displaySmall = display(base.displaySmall), headlineMedium = display(base.headlineMedium),
        headlineSmall = display(base.headlineSmall), titleLarge = display(base.titleLarge),
    )
    CompositionLocalProvider(LocalFsColors provides colors, LocalFsMono provides mono) {
        MaterialTheme(colorScheme = if (dark) FsDarkScheme else FsLightScheme, typography = typography, content = content)
    }
}

val LocalFsMono = androidx.compose.runtime.staticCompositionLocalOf<FontFamily> { FontFamily.Monospace }

private object FsType {
    @Composable fun label() = TextStyle(fontFamily = LocalFsMono.current, fontSize = 12.sp, lineHeight = 16.sp, letterSpacing = 0.06.em)
    @Composable fun heading() = TextStyle(fontFamily = LocalFsMono.current, fontWeight = FontWeight.SemiBold, fontSize = 14.sp, lineHeight = 20.sp, letterSpacing = 0.04.em)
    @Composable fun readout(size: Int) = TextStyle(fontFamily = LocalFsMono.current, fontSize = size.sp, lineHeight = (size + 4).sp, fontFeatureSettings = "tnum, zero")
}

// ------------------------------------------------------------------ signals

/** A state with a word and a shape. Color is the third cue, never the only one. */
enum class FsSignal { Danger, Caution, Ok, Info, Off, Stale, Predicted }

/**
 * A status chip: `CONT`, `ARMED`, `NOT USED`. Danger, caution and normal are filled the same on every background, like a
 * safety sign; the others are outlined. [icon] is a FusionSpace icon (product/icons/android/) drawn by the caller.
 */
@Composable
fun FsStatus(word: String, signal: FsSignal, modifier: Modifier = Modifier, icon: (@Composable () -> Unit)? = null) {
    val c = LocalFsColors.current
    val (fg, bg) = when (signal) {
        FsSignal.Danger -> c.onDangerFill to c.dangerFill
        FsSignal.Caution -> c.onCautionFill to c.cautionFill
        FsSignal.Ok -> c.onOkFill to c.okFill
        FsSignal.Info -> c.action to Color.Transparent
        FsSignal.Off -> c.inkMuted to Color.Transparent
        FsSignal.Stale -> c.inkMuted to c.surface
        FsSignal.Predicted -> c.predicted to Color.Transparent
    }
    val edge = when (signal) {
        FsSignal.Info -> Modifier.border(1.dp, c.action)
        FsSignal.Off, FsSignal.Stale -> Modifier.border(1.dp, c.ruleStrong)
        FsSignal.Predicted -> Modifier.dashedBorder(c.predicted)
        else -> Modifier
    }
    Row(
        modifier.background(bg).then(edge).heightIn(min = 24.dp).padding(horizontal = 8.dp)
            .clearAndSetSemantics { contentDescription = word },
        verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(6.dp),
    ) {
        if (signal == FsSignal.Stale) FsHatch(c.inkFaint, Modifier.width(8.dp).height(24.dp))
        icon?.invoke()
        Text(word.uppercase(), style = FsType.label().copy(fontWeight = FontWeight.SemiBold), color = fg)
    }
}

private fun Modifier.dashedBorder(color: Color) = this.drawBehind {
    drawRect(color, style = Stroke(width = 1.dp.toPx(), pathEffect = PathEffect.dashPathEffect(floatArrayOf(4.dp.toPx(), 2.dp.toPx()))))
}

/** 45° hatching, 1 dp lines every 6 dp: unavailable, stale or out of range (an ISO 128 section line). */
@Composable
fun FsHatch(color: Color, modifier: Modifier = Modifier) {
    Canvas(modifier) {
        val step = 6.dp.toPx()
        var x = -size.height
        while (x < size.width) {
            drawLine(color, Offset(x, size.height), Offset(x + size.height, 0f), strokeWidth = 1.dp.toPx())
            x += step
        }
    }
}

// ------------------------------------------------------------------ readouts

enum class FsReadoutKind { Measured, Predicted, Stale }

/**
 * A number someone came for: a label, the value with its unit, and a qualifier that says where it came from or how far to
 * trust it. Predicted values carry a dashed underline (drawn); stale ones turn muted with a hatched block.
 * [spokenUnit] is the unit as TalkBack should say it ("feet above ground level" for "ft AGL").
 */
@Composable
fun FsReadout(
    label: String, value: String, unit: String, modifier: Modifier = Modifier, qualifier: String? = null,
    kind: FsReadoutKind = FsReadoutKind.Measured, size: Int = {{READOUT}}, spokenUnit: String? = null,
) {
    val c = LocalFsColors.current
    val spoken = buildString {
        if (kind == FsReadoutKind.Predicted) append("predicted, ")
        append("$value ${spokenUnit ?: unit}")
        if (kind == FsReadoutKind.Stale) append(", stale")
        qualifier?.let { append(", $it") }
    }
    Column(modifier.semantics(mergeDescendants = true) { contentDescription = "$label, $spoken" }, verticalArrangement = Arrangement.spacedBy(4.dp)) {
        Text(label.uppercase(), style = FsType.label(), color = c.inkMuted)
        Row(verticalAlignment = Alignment.Bottom, horizontalArrangement = Arrangement.spacedBy(6.dp)) {
            if (kind == FsReadoutKind.Stale) FsHatch(c.inkFaint, Modifier.width(10.dp).height(size.dp).border(1.dp, c.ruleStrong))
            Text(
                value, style = FsType.readout(size), color = if (kind == FsReadoutKind.Stale) c.inkMuted else c.ink,
                modifier = if (kind == FsReadoutKind.Predicted) Modifier.predictedUnderline(c.predicted) else Modifier,
            )
            Text(unit, style = FsType.label().copy(letterSpacing = 0.em), color = c.inkMuted, modifier = Modifier.padding(bottom = 4.dp))
        }
        qualifier?.let { Text(it, style = MaterialTheme.typography.bodySmall, color = c.inkMuted) }
    }
}

private fun Modifier.predictedUnderline(color: Color) = this.drawBehind {
    val y = size.height - 1.dp.toPx()
    drawLine(color, Offset(0f, y), Offset(size.width, y), strokeWidth = 2.dp.toPx(),
        pathEffect = PathEffect.dashPathEffect(floatArrayOf(8.dp.toPx(), 4.dp.toPx())))
}

// ------------------------------------------------------------------ sheets and the title block

/** The top of a section: a 2 dp rule (the sheet's edge), its name, and `SHEET n / N`. */
@Composable
fun FsSheetHeader(name: String, number: Int, total: Int, modifier: Modifier = Modifier) {
    val c = LocalFsColors.current
    Column(modifier.fillMaxWidth(), verticalArrangement = Arrangement.spacedBy(8.dp)) {
        Box(Modifier.fillMaxWidth().height(2.dp).background(c.ink))
        Row(verticalAlignment = Alignment.Bottom) {
            Text(name.uppercase(), style = FsType.heading(), color = c.ink, modifier = Modifier.semantics { heading() })
            Spacer(Modifier.weight(1f))
            Text("SHEET $number / $total", style = FsType.label(), color = c.inkMuted,
                modifier = Modifier.clearAndSetSemantics { contentDescription = "Sheet $number of $total" })
        }
    }
}

/** One cell of the title block; a wide cell takes a row to itself. */
data class FsTitleCell(val key: String, val value: String, val wide: Boolean = false)

/** The About screen as a drawing's title block: owner, title, designation, revision, versions, data, licenses. */
@Composable
fun FsTitleBlock(cells: List<FsTitleCell>, modifier: Modifier = Modifier, mark: (@Composable () -> Unit)? = null) {
    val c = LocalFsColors.current
    val rows = buildList {
        var cur = mutableListOf<FsTitleCell>()
        for (cell in cells) {
            if (cell.wide) { if (cur.isNotEmpty()) { add(cur); cur = mutableListOf() }; add(listOf(cell)) }
            else { cur.add(cell); if (cur.size == 2) { add(cur); cur = mutableListOf() } }
        }
        if (cur.isNotEmpty()) add(cur)
    }
    Column(modifier.fillMaxWidth().background(c.surface).border(2.dp, c.ink)) {
        for (row in rows) {
            Row(Modifier.fillMaxWidth()) {
                for (cell in row) {
                    Column(
                        Modifier.weight(1f).border(0.5.dp, c.ruleStrong).padding(horizontal = 10.dp, vertical = 6.dp)
                            .semantics(mergeDescendants = true) {},
                        verticalArrangement = Arrangement.spacedBy(2.dp),
                    ) {
                        Text(cell.key.uppercase(), style = FsType.label().copy(fontSize = 11.sp, letterSpacing = 0.08.em), color = c.inkMuted)
                        Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                            if (cell.key == "Owner") mark?.invoke()
                            Text(cell.value, style = FsType.readout(14), color = c.ink)
                        }
                    }
                }
                if (row.size == 1 && !row[0].wide) Spacer(Modifier.weight(1f))
            }
        }
    }
}

// ------------------------------------------------------------------ device state

/** What the app asked the hardware to do, and what the hardware says it is. The app never assumes. */
@Composable
fun FsCommandedConfirmed(commanded: String?, confirmed: String, age: String, modifier: Modifier = Modifier) {
    val c = LocalFsColors.current
    Column(modifier.clearAndSetSemantics { contentDescription = "Commanded ${commanded ?: "nothing"}. Confirmed $confirmed, $age." },
        verticalArrangement = Arrangement.spacedBy(4.dp)) {
        Row { Text("COMMANDED", style = FsType.label(), color = c.inkMuted, modifier = Modifier.width(104.dp)); Text(commanded ?: "—", style = FsType.readout(15), color = c.ink) }
        Row { Text("CONFIRMED", style = FsType.label(), color = c.inkMuted, modifier = Modifier.width(104.dp)); Text("$confirmed · $age", style = FsType.readout(15), color = c.ink) }
    }
}

/** The device's state as a box: SAFE outlined, ARMED inverted (product/embedded.md). Nothing else uses the inverted box. */
@Composable
fun FsStateBox(armed: Boolean, modifier: Modifier = Modifier) {
    val c = LocalFsColors.current
    Text(
        if (armed) "ARMED" else "SAFE", style = FsType.readout(28).copy(fontWeight = FontWeight.SemiBold),
        color = if (armed) c.onDangerFill else c.ink,
        modifier = modifier.background(if (armed) c.dangerFill else Color.Transparent)
            .border(3.dp, if (armed) c.dangerFill else c.ink).padding(horizontal = 14.dp, vertical = 10.dp),
    )
}

// ------------------------------------------------------------------ held confirmation (arming)

/**
 * Arming from the app is a second step on top of the airframe's switch: a press held for {{HOLD_S}} s that shows the device's
 * designation (product/embedded.md). Letting go early cancels. TalkBack and Switch Access get the accessible alternative,
 * still two steps: a custom action that opens a confirmation. Put SAFE, one action, to its right.
 */
@Composable
fun FsHoldToConfirm(
    title: String, designation: String, onConfirmed: () -> Unit, modifier: Modifier = Modifier, holdMillis: Int = {{HOLD_MS}},
) {
    val c = LocalFsColors.current
    val haptics = LocalHapticFeedback.current
    val scope = rememberCoroutineScope()
    val progress = remember { Animatable(0f) }
    var confirming by remember { mutableStateOf(false) }
    Box(
        modifier
            .fillMaxWidth().heightIn(min = FS_GLOVE_TARGET_DP.dp)
            .background(c.surface).border(2.dp, c.ink)
            .pointerInput(holdMillis) {
                awaitEachGesture {
                    awaitFirstDown()
                    val run = scope.launch {
                        progress.animateTo(1f, tween(holdMillis, easing = LinearEasing))
                        haptics.performHapticFeedback(HapticFeedbackType.LongPress)
                        onConfirmed()
                    }
                    waitForUpOrCancellation()
                    run.cancel()
                    scope.launch { progress.animateTo(0f, tween(160)) }
                }
            }
            .semantics(mergeDescendants = true) {
                role = Role.Button
                contentDescription = "$title $designation. Press and hold for ${holdMillis / 1000} seconds."
                stateDescription = if (progress.value > 0f) "Holding" else ""
                customActions = listOf(CustomAccessibilityAction("$title with a confirmation") { confirming = true; true })
            },
    ) {
        Box(Modifier.fillMaxHeight().fillMaxWidth(progress.value).background(c.danger.copy(alpha = 0.10f)))
        Box(Modifier.align(Alignment.BottomStart).fillMaxWidth().height(8.dp).background(c.rule))
        Box(Modifier.align(Alignment.BottomStart).fillMaxWidth(progress.value).height(8.dp).background(c.danger))
        Column(Modifier.align(Alignment.CenterStart).padding(horizontal = 16.dp), verticalArrangement = Arrangement.spacedBy(6.dp)) {
            Text(title.uppercase(), style = FsType.heading().copy(fontSize = 18.sp), color = c.ink)
            Text("$designation · ${holdMillis / 1000} s", style = FsType.readout(14), color = c.ink)
            if (progress.value > 0f) Text("Keep holding", style = FsType.label().copy(fontWeight = FontWeight.SemiBold), color = c.danger)
        }
    }
    if (confirming) {
        AlertDialog(
            onDismissRequest = { confirming = false },
            title = { Text("$title $designation?") },
            text = { Text("The airframe's switch must already be on. SAFE stays one tap away.") },
            confirmButton = { TextButton(onClick = { confirming = false; onConfirmed() }) { Text(title, color = c.danger) } },
            dismissButton = { TextButton(onClick = { confirming = false }) { Text("Cancel") } },
        )
    }
}

// ------------------------------------------------------------------ freshness

/** How old a value may get before it shows as stale (product/data.md#live-telemetry), and the age every live value carries. */
object FsFreshness {
    const val FLIGHT_MS = {{STALE_FLIGHT_MS}}L
    const val WEATHER_MS = {{STALE_WEATHER_MS}}L
    fun isStale(ageMs: Long, limitMs: Long) = ageMs > limitMs
    fun age(ageMs: Long): String {
        val s = ageMs.coerceAtLeast(0) / 1000.0
        return when {
            s < 10 -> "${"%.1f".format(s)} s ago"
            s < 60 -> "${s.toInt()} s ago"
            s < 3600 -> "${(s / 60).toInt()} min ago"
            else -> "${(s / 3600).toInt()} h ago"
        }
    }
}

/** Field-size target: {{FIELD}} dp for controls used at the pad (about 15 mm). Keep the screen on with Modifier.keepScreenOn(). */
fun Modifier.fsFieldTarget() = this.heightIn(min = FS_FIELD_TARGET_DP.dp)
