// SPDX-License-Identifier: Apache-2.0 · Copyright 2026 Neer Patel
// A FusionSpace Live Update, worked through: a flight from the pad to the landing site
// (product/mobile/glance/android-live-update.png). Generated by tools/build/kit_mobile.py from source/product/mobile/;
// edit there. Android only (android.app.Notification); compile against API 37, run on Android 16 (API 36) and later.
//
// Rules (product/mobile.md#glanceable-surfaces): the system draws the card, so the app gives words, numbers with their
// units and a progress model, never custom views or colorized backgrounds (a promoted notification can't have either). The
// status-bar chip gets {{CHIP_CHARS}} characters at most. On Android 17 the state rides on a semantic color that matches the
// signal colors: SAFE for Aurora (normal), CAUTION for Sodium, DANGER for Flare, INFO for the action color.
//
// Manifest: <uses-permission android:name="android.permission.POST_PROMOTED_NOTIFICATIONS" /> (not a runtime permission;
// the user can still turn Live Updates off for the app: check NotificationManager.canPostPromotedNotifications()).
package co.fusionspace.design

import android.app.Notification
import android.content.Context
import android.os.Build
import android.os.Bundle

/** What the flight is doing now. Times are seconds from liftoff; the events come from the flight computer's report. */
data class FsFlightNow(
    val flight: String,                    // "Flight 04"
    val phase: String,                     // "under the main"
    val altitudeFt: Int, val verticalFtS: Int,
    val distanceFt: Int?, val bearingTrue: Int?,
    val liftoffEpochMs: Long,
    val burnoutS: Float, val apogeeS: Float, val mainS: Float, val expectedLandingS: Float, val nowS: Float,
    val signal: FsSignal = FsSignal.Ok,
)

object FsLiveUpdate {
    private const val SCALE = 10              // progress units per second, so short phases still get a segment

    /** The chip: the one number that matters, with its unit, in {{CHIP_CHARS}} characters at most ("612 ft", "9876 ft"). Never
     *  cut off: a longer number goes to thousands ("12k ft"), so the chip can't read "12345 f". */
    fun chipText(now: FsFlightNow): String {
        val ft = now.altitudeFt
        return listOf("$ft\u00A0ft", "${Math.round(ft / 1000.0)}k\u00A0ft").firstOrNull { it.length <= {{CHIP_CHARS}} } ?: "${Math.round(ft / 1000.0)}k"
    }

    fun build(context: Context, channelId: String, smallIcon: Int, trackerIcon: Int, now: FsFlightNow): Notification {
        val where = listOfNotNull(
            "${"%,d".format(now.altitudeFt)}\u00A0ft\u00A0AGL",
            "${if (now.verticalFtS < 0) "−" else "+"}${kotlin.math.abs(now.verticalFtS)}\u00A0ft/s",
            if (now.distanceFt != null && now.bearingTrue != null) "${"%,d".format(now.distanceFt)}\u00A0ft at ${"%03d".format(now.bearingTrue)}°\u00A0T" else null,
        ).joinToString(" · ")
        val b = Notification.Builder(context, channelId)
            .setSmallIcon(smallIcon)
            .setContentTitle("${now.flight} · ${now.phase}")
            .setContentText(where)
            .setOngoing(true)
            .setOnlyAlertOnce(true)
            .setCategory(Notification.CATEGORY_PROGRESS)
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.BAKLAVA) {
            b.setShortCriticalText(chipText(now))
            if (Build.VERSION.SDK_INT_FULL >= Build.VERSION_CODES_FULL.BAKLAVA_1) b.setRequestPromotedOngoing(true)
            else b.addExtras(Bundle().apply { putBoolean("android.requestPromotedOngoing", true) })
        }
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.CINNAMON_BUN) b.setStyle(metricStyle(now))
        else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.BAKLAVA) b.setStyle(progressStyle(context, trackerIcon, now))
        return b.build()
    }

    /** Android 16: the flight's phases as segments (boost, coast, drogue, main), apogee and main as points, the rocket as the tracker. */
    private fun progressStyle(context: Context, trackerIcon: Int, n: FsFlightNow): Notification.ProgressStyle {
        val edges = listOf(0f, n.burnoutS, n.apogeeS, n.mainS, n.expectedLandingS)
        val segments = edges.zipWithNext { a, b -> Notification.ProgressStyle.Segment(((b - a) * SCALE).toInt().coerceAtLeast(1)) }
        return Notification.ProgressStyle()
            .setStyledByProgress(true)
            .setProgressSegments(segments)
            .setProgressPoints(listOf(n.apogeeS, n.mainS).map { Notification.ProgressStyle.Point((it * SCALE).toInt()) })
            .setProgressTrackerIcon(android.graphics.drawable.Icon.createWithResource(context, trackerIcon))
            .setProgress((n.nowS.coerceAtMost(n.expectedLandingS) * SCALE).toInt())
    }

    /** Android 17: three values with their units, the time since liftoff counting on its own, and the state as a semantic color. */
    private fun metricStyle(n: FsFlightNow): Notification.MetricStyle {
        val style = semantic(n.signal)
        val metrics = buildList {
            add(Notification.Metric(Notification.Metric.FixedInt(n.altitudeFt, "ft"), "Altitude", style))
            if (n.distanceFt != null) add(Notification.Metric(Notification.Metric.FixedInt(n.distanceFt, "ft"), "From you", style))
            add(Notification.Metric(Notification.Metric.TimeDifference.forStopwatch(java.time.Instant.ofEpochMilli(n.liftoffEpochMs),
                Notification.Metric.TimeDifference.FORMAT_CHRONOMETER), "Since liftoff"))
        }
        return Notification.MetricStyle().setMetrics(metrics).setCriticalMetric(0)
    }

    /** The FusionSpace signals as Android 17's semantic styles. Predicted and stale have none: they stay unspecified. */
    fun semantic(s: FsSignal): Int = when (s) {
        FsSignal.Ok -> Notification.SEMANTIC_STYLE_SAFE
        FsSignal.Caution -> Notification.SEMANTIC_STYLE_CAUTION
        FsSignal.Danger -> Notification.SEMANTIC_STYLE_DANGER
        FsSignal.Info -> Notification.SEMANTIC_STYLE_INFO
        else -> Notification.SEMANTIC_STYLE_UNSPECIFIED
    }
}
