/* SPDX-License-Identifier: Apache-2.0 · Copyright 2026 Neer Patel */
/* FusionSpace styles for LVGL. Generated by tools/build/kit_product.py. */
#ifndef FS_LVGL_STYLES_H
#define FS_LVGL_STYLES_H
#include "lvgl.h"
extern lv_style_t fs_style_screen, fs_style_panel, fs_style_button, fs_style_button_pressed, fs_style_label_muted,
                  fs_style_state_safe, fs_style_state_armed, fs_style_chip_ok, fs_style_chip_caution, fs_style_chip_danger;
void fs_lvgl_styles_init(void);
#endif
