/* FusionSpace styles for LVGL 9 (also LVGL 8: the lv_style_set_* calls are the same). Generated by
   tools/build/kit_product.py. Square corners, 1 px borders, no shadows, the dark roles from fusionspace_ui.h.

   Use: fs_lvgl_styles_init(); then lv_obj_add_style(obj, &fs_style_panel, 0); and so on, or apply them in a theme's
   apply callback built on the simple theme (lv_theme_simple_init). */
#include "lvgl.h"
#include "fusionspace_ui.h"

lv_style_t fs_style_screen, fs_style_panel, fs_style_button, fs_style_button_pressed, fs_style_label_muted,
           fs_style_state_safe, fs_style_state_armed, fs_style_chip_ok, fs_style_chip_caution, fs_style_chip_danger;

static void base(lv_style_t *s)
{
    lv_style_init(s);
    lv_style_set_radius(s, 0);
    lv_style_set_shadow_width(s, 0);
}

void fs_lvgl_styles_init(void)
{
    base(&fs_style_screen);
    lv_style_set_bg_color(&fs_style_screen, lv_color_hex(FS_CANVAS_RGB888));
    lv_style_set_bg_opa(&fs_style_screen, LV_OPA_COVER);
    lv_style_set_text_color(&fs_style_screen, lv_color_hex(FS_INK_RGB888));

    base(&fs_style_panel);
    lv_style_set_bg_color(&fs_style_panel, lv_color_hex(FS_SURFACE_RGB888));
    lv_style_set_bg_opa(&fs_style_panel, LV_OPA_COVER);
    lv_style_set_border_color(&fs_style_panel, lv_color_hex(FS_RULE_RGB888));
    lv_style_set_border_width(&fs_style_panel, 1);
    lv_style_set_pad_all(&fs_style_panel, 8);

    base(&fs_style_button);                      /* primary: ink fill, canvas text */
    lv_style_set_bg_color(&fs_style_button, lv_color_hex(FS_INK_RGB888));
    lv_style_set_bg_opa(&fs_style_button, LV_OPA_COVER);
    lv_style_set_text_color(&fs_style_button, lv_color_hex(FS_CANVAS_RGB888));
    lv_style_set_border_width(&fs_style_button, 0);
    lv_style_set_pad_hor(&fs_style_button, 16);
    lv_style_set_pad_ver(&fs_style_button, 8);

    base(&fs_style_button_pressed);              /* pressed: the action colour */
    lv_style_set_bg_color(&fs_style_button_pressed, lv_color_hex(FS_ACTION_RGB888));
    lv_style_set_text_color(&fs_style_button_pressed, lv_color_hex(FS_ON_ACTION_RGB888));

    base(&fs_style_label_muted);
    lv_style_set_text_color(&fs_style_label_muted, lv_color_hex(FS_INK_MUTED_RGB888));

    base(&fs_style_state_safe);                  /* SAFE: an outline box */
    lv_style_set_border_color(&fs_style_state_safe, lv_color_hex(FS_INK_RGB888));
    lv_style_set_border_width(&fs_style_state_safe, 1);
    lv_style_set_pad_hor(&fs_style_state_safe, 4);

    base(&fs_style_state_armed);                 /* ARMED: an inverted box in the danger fill */
    lv_style_set_bg_color(&fs_style_state_armed, lv_color_hex(FS_DANGER_FILL_RGB888));
    lv_style_set_bg_opa(&fs_style_state_armed, LV_OPA_COVER);
    lv_style_set_text_color(&fs_style_state_armed, lv_color_hex(FS_ON_DANGER_FILL_RGB888));
    lv_style_set_pad_hor(&fs_style_state_armed, 4);

    base(&fs_style_chip_ok);
    lv_style_set_bg_color(&fs_style_chip_ok, lv_color_hex(FS_OK_FILL_RGB888));
    lv_style_set_bg_opa(&fs_style_chip_ok, LV_OPA_COVER);
    lv_style_set_text_color(&fs_style_chip_ok, lv_color_hex(FS_ON_OK_FILL_RGB888));
    lv_style_set_pad_hor(&fs_style_chip_ok, 4);

    base(&fs_style_chip_caution);
    lv_style_set_bg_color(&fs_style_chip_caution, lv_color_hex(FS_CAUTION_FILL_RGB888));
    lv_style_set_bg_opa(&fs_style_chip_caution, LV_OPA_COVER);
    lv_style_set_text_color(&fs_style_chip_caution, lv_color_hex(FS_ON_CAUTION_FILL_RGB888));
    lv_style_set_pad_hor(&fs_style_chip_caution, 4);

    base(&fs_style_chip_danger);
    lv_style_set_bg_color(&fs_style_chip_danger, lv_color_hex(FS_DANGER_FILL_RGB888));
    lv_style_set_bg_opa(&fs_style_chip_danger, LV_OPA_COVER);
    lv_style_set_text_color(&fs_style_chip_danger, lv_color_hex(FS_ON_DANGER_FILL_RGB888));
    lv_style_set_pad_hor(&fs_style_chip_danger, 4);
}
