// SPDX-License-Identifier: Apache-2.0 · Copyright 2026 Neer Patel
// A FusionSpace tile and complication for Wear OS, worked through: the way to a landed rocket
// (product/watch/faces/wearos-tiles.png, wearos-face.png). Generated by tools/build/kit_watch.py from source/product/watch/;
// edit there. Tiles: ProtoLayout Material 3. Complications: watchface-complications-data-source.
//
// Rules (product/watch.md#complications-smart-stack-and-tiles): one readout with its unit and its age, one action; a tile
// is a glance, so anything that moves (the arrow, a live altitude) belongs in the app.
package co.fusionspace.design.wear

import androidx.compose.ui.graphics.toArgb
import androidx.concurrent.futures.ResolvableFuture
import androidx.wear.protolayout.ActionBuilders
import androidx.wear.protolayout.LayoutElementBuilders
import androidx.wear.protolayout.ModifiersBuilders
import androidx.wear.protolayout.ResourceBuilders
import androidx.wear.protolayout.TimelineBuilders
import androidx.wear.protolayout.TypeBuilders
import androidx.wear.protolayout.expression.DynamicBuilders.DynamicInstant
import androidx.wear.protolayout.expression.DynamicBuilders.DynamicString
import androidx.wear.protolayout.material3.ColorScheme
import androidx.wear.protolayout.material3.Typography
import androidx.wear.protolayout.material3.materialScope
import androidx.wear.protolayout.material3.primaryLayout
import androidx.wear.protolayout.material3.text
import androidx.wear.protolayout.material3.textEdgeButton
import androidx.wear.protolayout.modifiers.LayoutModifier
import androidx.wear.protolayout.modifiers.clearSemantics
import androidx.wear.protolayout.modifiers.contentDescription
import androidx.wear.protolayout.types.LayoutColor
import androidx.wear.protolayout.types.LayoutString
import androidx.wear.protolayout.types.layoutString
import androidx.wear.tiles.RequestBuilders
import androidx.wear.tiles.TileBuilders
import androidx.wear.tiles.TileService
import androidx.wear.watchface.complications.data.ComplicationData
import androidx.wear.watchface.complications.data.ComplicationType
import androidx.wear.watchface.complications.data.CountUpTimeReference
import androidx.wear.watchface.complications.data.LongTextComplicationData
import androidx.wear.watchface.complications.data.PlainComplicationText
import androidx.wear.watchface.complications.data.RangedValueComplicationData
import androidx.wear.watchface.complications.data.ShortTextComplicationData
import androidx.wear.watchface.complications.data.TimeDifferenceComplicationText
import androidx.wear.watchface.complications.data.TimeDifferenceStyle
import androidx.wear.watchface.complications.datasource.ComplicationRequest
import androidx.wear.watchface.complications.datasource.SuspendingComplicationDataSourceService
import com.google.common.util.concurrent.ListenableFuture
import java.time.Instant

/**
 * What the tile and complications show: the last fix the app saved. They never fetch at the field. [fixedAtMs] is when the
 * fix was taken (epoch milliseconds): the age is counted from it by the watch itself, so it never freezes at "4 s".
 */
data class FsFindSnapshot(val name: String, val phase: String, val distanceFt: Int, val bearingTrue: Int, val fixedAtMs: Long,
                          val altitudeFt: Int?, val apogeeFt: Int?) {
    /** One sentence for TalkBack, whatever the surface shows: "Vega, landed, 1,352 feet, bearing 62 degrees true". */
    val spoken: String get() = "$name, ${phase.lowercase()}, ${"%,d".format(distanceFt)} feet, bearing $bearingTrue degrees true"
}

private fun example() = FsFindSnapshot("Vega", "LANDED", 1352, 62, System.currentTimeMillis() - 4_000, null, 5104)

/**
 * The fix's age counting up on the watch, between tile updates: "4 s ago", "3 min ago", "2 h ago" or, for TalkBack,
 * "4 seconds", "3 minutes". [static] is the value at the time of the request, for renderers without dynamic values.
 */
private fun tileAge(fixedAtMs: Long, words: Boolean): Pair<String, DynamicString> {
    val ageS = ((System.currentTimeMillis() - fixedAtMs) / 1000).coerceAtLeast(0)
    fun unit(n: Long, short: String, word: String) = "$n" + if (words) " $word" + (if (n == 1L) "" else "s") else "\u00A0$short ago"
    val static = when { ageS < 60 -> unit(ageS, "s", "second"); ageS < 3600 -> unit(ageS / 60, "min", "minute"); else -> unit(ageS / 3600, "h", "hour") }
    val age = DynamicInstant.withSecondsPrecision(Instant.ofEpochMilli(fixedAtMs)).durationUntil(DynamicInstant.platformTimeWithSecondsPrecision())
    fun c(text: String) = DynamicString.constant(text)
    fun part(n: androidx.wear.protolayout.expression.DynamicBuilders.DynamicInt32, short: String, word: String): DynamicString =
        if (!words) n.format().concat(c("\u00A0$short ago"))
        else DynamicString.onCondition(n.eq(1)).use(n.format().concat(c(" $word"))).elseUse(n.format().concat(c(" ${word}s")))
    val dynamic = DynamicString.onCondition(age.toIntSeconds().lt(60)).use(part(age.toIntSeconds(), "s", "second"))
        .elseUse(DynamicString.onCondition(age.toIntMinutes().lt(60)).use(part(age.toIntMinutes(), "min", "minute"))
            .elseUse(part(age.toIntHours(), "h", "hour")))
    return static to dynamic
}

private fun prop(static: String, dynamic: DynamicString) = TypeBuilders.StringProp.Builder(static).setDynamicValue(dynamic).build()
private fun semantics(description: TypeBuilders.StringProp) = ModifiersBuilders.Modifiers.Builder()
    .setSemantics(ModifiersBuilders.Semantics.Builder().setContentDescription(description).build()).build()

/** Find: title slot (rocket and phase), main slot (distance and bearing with the fix's age), edge button (open the app). */
open class FsFindTileService : TileService() {
    open fun snapshot(): FsFindSnapshot = example()

    /** The activity the edge button opens, a class name in this app: by default `<package>.FindActivity`. */
    open val findActivityClass: String get() = "$packageName.FindActivity"

    override fun onTileRequest(requestParams: RequestBuilders.TileRequest): ListenableFuture<TileBuilders.Tile> {
        val s = snapshot()
        val (age, ageLive) = tileAge(s.fixedAtMs, words = false)
        val (spokenAge, spokenAgeLive) = tileAge(s.fixedAtMs, words = true)
        val bearing = "%03d°\u00A0T · fix ".format(s.bearingTrue)
        val quiet = LayoutModifier.clearSemantics()  // the column's sentence says it; its texts aren't read again
        val open = ModifiersBuilders.Clickable.Builder().setId("find").setOnClick(
            ActionBuilders.LaunchAction.Builder().setAndroidActivity(
                ActionBuilders.AndroidActivity.Builder().setPackageName(packageName).setClassName(findActivityClass).build()
            ).build()
        ).build()
        // The static FusionSpace scheme, not the watch's dynamic one: the colors mean something (product/watch.md).
        val layout = materialScope(this, requestParams.deviceConfiguration, allowDynamicTheme = false, defaultColorScheme = fsTileColors()) {
            primaryLayout(
                titleSlot = {
                    text("${s.name.uppercase()} · ${s.phase}".layoutString, color = colorScheme.onSurfaceVariant,
                        modifier = LayoutModifier.contentDescription("${s.name}, ${s.phase.lowercase()}"))
                },
                // One readout with its unit and its age: the distance, then the bearing and how old the fix is, the age
                // counting on the watch. TalkBack hears it as one sentence: "1,352 feet, bearing 62 degrees true, fix 4
                // seconds old", not "062 degrees T".
                mainSlot = {
                    LayoutElementBuilders.Column.Builder()
                        .setModifiers(semantics(prop(
                            "${"%,d".format(s.distanceFt)} feet, bearing ${s.bearingTrue} degrees true, fix $spokenAge old",
                            DynamicString.constant("${"%,d".format(s.distanceFt)} feet, bearing ${s.bearingTrue} degrees true, fix ")
                                .concat(spokenAgeLive).concat(DynamicString.constant(" old")),
                        )))
                        .addContent(
                            LayoutElementBuilders.Row.Builder()
                                .setVerticalAlignment(LayoutElementBuilders.VERTICAL_ALIGN_BOTTOM)
                                .addContent(text("%,d".format(s.distanceFt).layoutString, typography = Typography.NUMERAL_MEDIUM, color = colorScheme.onSurface, modifier = quiet))
                                .addContent(text(" ft".layoutString, typography = Typography.LABEL_MEDIUM, color = colorScheme.onSurfaceVariant, modifier = quiet))
                                .build(),
                        )
                        .addContent(text(LayoutString(bearing + age, DynamicString.constant(bearing).concat(ageLive),
                            TypeBuilders.StringLayoutConstraint.Builder(bearing + "59\u00A0min ago").build()),
                            typography = Typography.BODY_MEDIUM, color = colorScheme.onSurfaceVariant, modifier = quiet))
                        .build()
                },
                bottomSlot = { textEdgeButton(onClick = open, labelContent = { text("Find".layoutString) }) },
            )
        }
        val tile = TileBuilders.Tile.Builder()
            .setResourcesVersion("1")
            .setFreshnessIntervalMillis({{TILE_FRESH_MS}})
            .setTileTimeline(TimelineBuilders.Timeline.fromLayoutElement(layout))
            .build()
        return ResolvableFuture.create<TileBuilders.Tile>().apply { set(tile) }
    }

    override fun onTileResourcesRequest(requestParams: RequestBuilders.ResourcesRequest): ListenableFuture<ResourceBuilders.Resources> =
        ResolvableFuture.create<ResourceBuilders.Resources>().apply { set(ResourceBuilders.Resources.Builder().setVersion("1").build()) }
}

/** The dark roles as a ProtoLayout Material 3 scheme: the action color for the edge button, black behind everything. */
private fun fsTileColors(): ColorScheme {
    val c = FsWearColors
    fun lc(color: androidx.compose.ui.graphics.Color) = LayoutColor(color.toArgb())
    return ColorScheme(
        primary = lc(c.action), primaryDim = lc(c.action), primaryContainer = lc(c.surface), onPrimary = lc(c.onAction),
        onPrimaryContainer = lc(c.ink), secondary = lc(c.inkMuted), secondaryDim = lc(c.inkMuted), secondaryContainer = lc(c.surface),
        onSecondary = lc(c.canvas), onSecondaryContainer = lc(c.ink), tertiary = lc(c.predicted), tertiaryDim = lc(c.predicted),
        tertiaryContainer = lc(c.surface), onTertiary = lc(c.canvas), onTertiaryContainer = lc(c.predicted),
        surfaceContainerLow = lc(c.canvas), surfaceContainer = lc(c.surface), surfaceContainerHigh = lc(c.rule),
        onSurface = lc(c.ink), onSurfaceVariant = lc(c.inkMuted), outline = lc(c.ruleStrong), outlineVariant = lc(c.rule),
        background = lc(androidx.compose.ui.graphics.Color.Black), onBackground = lc(c.ink),
        error = lc(c.dangerFill), errorDim = lc(c.dangerFill), errorContainer = lc(c.dangerFill), onError = lc(c.onDangerFill),
        onErrorContainer = lc(c.onDangerFill),
    )
}

/** SHORT_TEXT (distance), LONG_TEXT (name, distance, bearing), RANGED_VALUE (altitude on the way down). */
open class FsFindComplicationService : SuspendingComplicationDataSourceService() {
    open fun snapshot(): FsFindSnapshot = example()

    override suspend fun onComplicationRequest(request: ComplicationRequest): ComplicationData? = data(request.complicationType, snapshot())

    override fun getPreviewData(type: ComplicationType): ComplicationData? = data(type, example())

    private fun data(type: ComplicationType, s: FsFindSnapshot): ComplicationData? {
        // One sentence for TalkBack whatever the slot shows, the age counting up on the watch ("^1"): "Vega, landed, 1,352
        // feet, bearing 62 degrees true, fix less than 1 min old" (the words VoiceOver reads on Apple Watch). Wear's word
        // styles count in whole minutes, rounded up, hence "less than" (Apple's Always On says "<1min" the same way).
        val spoken = TimeDifferenceComplicationText.Builder(TimeDifferenceStyle.WORDS_SINGLE_UNIT, CountUpTimeReference(Instant.ofEpochMilli(s.fixedAtMs)))
            .setText("${s.spoken}, fix less than ^1 old").setDisplayAsNow(false).build()
        return when (type) {
            ComplicationType.SHORT_TEXT -> ShortTextComplicationData.Builder(
                PlainComplicationText.Builder("%,d\u00A0ft".format(s.distanceFt)).build(), spoken,
            ).setTitle(PlainComplicationText.Builder("%03d°".format(s.bearingTrue)).build()).build()
            ComplicationType.LONG_TEXT -> LongTextComplicationData.Builder(
                PlainComplicationText.Builder("${s.name} %,d\u00A0ft at %03d°\u00A0T".format(s.distanceFt, s.bearingTrue)).build(), spoken,
            ).build()
            ComplicationType.RANGED_VALUE -> if (s.altitudeFt != null && s.apogeeFt != null) RangedValueComplicationData.Builder(
                s.altitudeFt.toFloat(), 0f, s.apogeeFt.toFloat(),
                PlainComplicationText.Builder("${s.name}, ${s.phase.lowercase()}, altitude ${"%,d".format(s.altitudeFt)} feet above ground, apogee ${"%,d".format(s.apogeeFt)} feet").build(),
            ).setText(PlainComplicationText.Builder("${s.altitudeFt}").build())
                .setTitle(PlainComplicationText.Builder("ft AGL").build()).build() else null
            else -> null
        }
    }
}
