// SPDX-License-Identifier: Apache-2.0 · Copyright 2026 Neer Patel
// A FusionSpace tile and complication for Wear OS, worked through: the way to a landed rocket
// (product/watch/faces/wearos-tiles.png, wearos-face.png). Generated by tools/build/kit_watch.py from source/product/watch/;
// edit there. Tiles: ProtoLayout Material 3. Complications: watchface-complications-data-source.
//
// Rules (product/watch.md#complications-smart-stack-and-tiles): one readout with its unit and its age, one action; a tile
// is a glance, so anything that moves (the arrow, a live altitude) belongs in the app.
package co.fusionspace.design.wear

import androidx.compose.ui.graphics.toArgb
import androidx.concurrent.futures.ResolvableFuture
import androidx.wear.protolayout.ActionBuilders
import androidx.wear.protolayout.LayoutElementBuilders
import androidx.wear.protolayout.ModifiersBuilders
import androidx.wear.protolayout.ResourceBuilders
import androidx.wear.protolayout.TimelineBuilders
import androidx.wear.protolayout.material3.ColorScheme
import androidx.wear.protolayout.material3.Typography
import androidx.wear.protolayout.material3.materialScope
import androidx.wear.protolayout.material3.primaryLayout
import androidx.wear.protolayout.material3.text
import androidx.wear.protolayout.material3.textEdgeButton
import androidx.wear.protolayout.types.LayoutColor
import androidx.wear.protolayout.types.layoutString
import androidx.wear.tiles.RequestBuilders
import androidx.wear.tiles.TileBuilders
import androidx.wear.tiles.TileService
import androidx.wear.watchface.complications.data.ComplicationData
import androidx.wear.watchface.complications.data.ComplicationType
import androidx.wear.watchface.complications.data.LongTextComplicationData
import androidx.wear.watchface.complications.data.PlainComplicationText
import androidx.wear.watchface.complications.data.RangedValueComplicationData
import androidx.wear.watchface.complications.data.ShortTextComplicationData
import androidx.wear.watchface.complications.datasource.ComplicationRequest
import androidx.wear.watchface.complications.datasource.SuspendingComplicationDataSourceService
import com.google.common.util.concurrent.ListenableFuture

/** What the tile and complications show: the last fix the app saved. They never fetch at the field. */
data class FsFindSnapshot(val name: String, val phase: String, val distanceFt: Int, val bearingTrue: Int, val fixAge: String,
                          val altitudeFt: Int?, val apogeeFt: Int?)

private val EXAMPLE = FsFindSnapshot("Vega", "LANDED", 1352, 62, "4\u00A0s ago", null, 5104)

/** Find: title slot (rocket and phase), main slot (distance and bearing with the fix's age), edge button (open the app). */
open class FsFindTileService : TileService() {
    open fun snapshot(): FsFindSnapshot = EXAMPLE

    /** The activity the edge button opens, a class name in this app: by default `<package>.FindActivity`. */
    open val findActivityClass: String get() = "$packageName.FindActivity"

    override fun onTileRequest(requestParams: RequestBuilders.TileRequest): ListenableFuture<TileBuilders.Tile> {
        val s = snapshot()
        val open = ModifiersBuilders.Clickable.Builder().setId("find").setOnClick(
            ActionBuilders.LaunchAction.Builder().setAndroidActivity(
                ActionBuilders.AndroidActivity.Builder().setPackageName(packageName).setClassName(findActivityClass).build()
            ).build()
        ).build()
        // The static FusionSpace scheme, not the watch's dynamic one: the colors mean something (product/watch.md).
        val layout = materialScope(this, requestParams.deviceConfiguration, allowDynamicTheme = false, defaultColorScheme = fsTileColors()) {
            primaryLayout(
                titleSlot = { text("${s.name.uppercase()} · ${s.phase}".layoutString, color = colorScheme.onSurfaceVariant) },
                // One readout with its unit and its age: the distance, then the bearing and how old the fix is.
                mainSlot = {
                    LayoutElementBuilders.Column.Builder()
                        .addContent(
                            LayoutElementBuilders.Row.Builder()
                                .setVerticalAlignment(LayoutElementBuilders.VERTICAL_ALIGN_BOTTOM)
                                .addContent(text("%,d".format(s.distanceFt).layoutString, typography = Typography.NUMERAL_MEDIUM, color = colorScheme.onSurface))
                                .addContent(text(" ft".layoutString, typography = Typography.LABEL_MEDIUM, color = colorScheme.onSurfaceVariant))
                                .build(),
                        )
                        .addContent(text("%03d°\u00A0T · fix %s".format(s.bearingTrue, s.fixAge).layoutString,
                            typography = Typography.BODY_MEDIUM, color = colorScheme.onSurfaceVariant))
                        .build()
                },
                bottomSlot = { textEdgeButton(onClick = open, labelContent = { text("Find".layoutString) }) },
            )
        }
        val tile = TileBuilders.Tile.Builder()
            .setResourcesVersion("1")
            .setFreshnessIntervalMillis({{TILE_FRESH_MS}})
            .setTileTimeline(TimelineBuilders.Timeline.fromLayoutElement(layout))
            .build()
        return ResolvableFuture.create<TileBuilders.Tile>().apply { set(tile) }
    }

    override fun onTileResourcesRequest(requestParams: RequestBuilders.ResourcesRequest): ListenableFuture<ResourceBuilders.Resources> =
        ResolvableFuture.create<ResourceBuilders.Resources>().apply { set(ResourceBuilders.Resources.Builder().setVersion("1").build()) }
}

/** The dark roles as a ProtoLayout Material 3 scheme: the action color for the edge button, black behind everything. */
private fun fsTileColors(): ColorScheme {
    val c = FsWearColors
    fun lc(color: androidx.compose.ui.graphics.Color) = LayoutColor(color.toArgb())
    return ColorScheme(
        primary = lc(c.action), primaryDim = lc(c.action), primaryContainer = lc(c.surface), onPrimary = lc(c.onAction),
        onPrimaryContainer = lc(c.ink), secondary = lc(c.inkMuted), secondaryDim = lc(c.inkMuted), secondaryContainer = lc(c.surface),
        onSecondary = lc(c.canvas), onSecondaryContainer = lc(c.ink), tertiary = lc(c.predicted), tertiaryDim = lc(c.predicted),
        tertiaryContainer = lc(c.surface), onTertiary = lc(c.canvas), onTertiaryContainer = lc(c.predicted),
        surfaceContainerLow = lc(c.canvas), surfaceContainer = lc(c.surface), surfaceContainerHigh = lc(c.rule),
        onSurface = lc(c.ink), onSurfaceVariant = lc(c.inkMuted), outline = lc(c.ruleStrong), outlineVariant = lc(c.rule),
        background = lc(androidx.compose.ui.graphics.Color.Black), onBackground = lc(c.ink),
        error = lc(c.dangerFill), errorDim = lc(c.dangerFill), errorContainer = lc(c.dangerFill), onError = lc(c.onDangerFill),
        onErrorContainer = lc(c.onDangerFill),
    )
}

/** SHORT_TEXT (distance), LONG_TEXT (name, distance, bearing), RANGED_VALUE (altitude on the way down). */
open class FsFindComplicationService : SuspendingComplicationDataSourceService() {
    open fun snapshot(): FsFindSnapshot = EXAMPLE

    override suspend fun onComplicationRequest(request: ComplicationRequest): ComplicationData? = data(request.complicationType, snapshot())

    override fun getPreviewData(type: ComplicationType): ComplicationData? = data(type, EXAMPLE)

    private fun data(type: ComplicationType, s: FsFindSnapshot): ComplicationData? {
        val spoken = PlainComplicationText.Builder("${s.name}: ${s.distanceFt} feet, bearing ${s.bearingTrue} degrees true, fix ${s.fixAge}").build()
        return when (type) {
            ComplicationType.SHORT_TEXT -> ShortTextComplicationData.Builder(
                PlainComplicationText.Builder("%,d\u00A0ft".format(s.distanceFt)).build(), spoken,
            ).setTitle(PlainComplicationText.Builder("%03d°".format(s.bearingTrue)).build()).build()
            ComplicationType.LONG_TEXT -> LongTextComplicationData.Builder(
                PlainComplicationText.Builder("${s.name} %,d\u00A0ft at %03d°\u00A0T".format(s.distanceFt, s.bearingTrue)).build(), spoken,
            ).build()
            ComplicationType.RANGED_VALUE -> if (s.altitudeFt != null && s.apogeeFt != null) RangedValueComplicationData.Builder(
                s.altitudeFt.toFloat(), 0f, s.apogeeFt.toFloat(),
                PlainComplicationText.Builder("Altitude ${s.altitudeFt} feet above ground").build(),
            ).setText(PlainComplicationText.Builder("${s.altitudeFt}").build())
                .setTitle(PlainComplicationText.Builder("ft AGL").build()).build() else null
            else -> null
        }
    }
}
