// SPDX-License-Identifier: Apache-2.0 · Copyright 2026 Neer Patel
// FusionSpace parts for Wear OS (Compose for Wear OS, Material 3). Generated by tools/build/kit_watch.py from
// source/product/watch/; edit there. Standalone: the colors are the dark roles, written in below from the same values as
// product/tokens/ (a Wear app doesn't carry the phone's Material 3, so it can't use FusionSpaceColors.kt).
//
// A watch finds, glances and taps the wrist (product/watch.md). It never commands hardware: nothing here sends ARM, SAFE,
// FIRE or a configuration change.
package co.fusionspace.design.wear

import android.app.PendingIntent
import android.content.Context
import android.os.VibrationEffect
import android.os.Vibrator
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.graphics.drawscope.rotate
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.semantics.clearAndSetSemantics
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.em
import androidx.compose.ui.unit.sp
import androidx.core.app.NotificationCompat
import androidx.wear.compose.foundation.AmbientMode
import androidx.wear.compose.foundation.LocalAmbientModeManager
import androidx.wear.compose.foundation.lazy.TransformingLazyColumn
import androidx.wear.compose.foundation.lazy.rememberTransformingLazyColumnState
import androidx.wear.compose.material3.AppScaffold
import androidx.wear.compose.material3.ColorScheme
import androidx.wear.compose.material3.EdgeButton
import androidx.wear.compose.material3.EdgeButtonSize
import androidx.wear.compose.material3.MaterialTheme
import androidx.wear.compose.material3.ScreenScaffold
import androidx.wear.compose.material3.Text
import androidx.wear.compose.material3.TimeText
import androidx.wear.ongoing.OngoingActivity
import androidx.wear.ongoing.Status
import kotlin.math.PI
import kotlin.math.acos
import kotlin.math.cos
import kotlin.math.sin
import kotlin.math.sqrt

// ------------------------------------------------------------------ colors and theme

/** The dark roles and signal fills (product/foundations.md). A watch is an emissive screen: always dark. */
object FsWearColors {
{{COLORS}}
}

/**
 * Material 3 for Wear OS with the static FusionSpace scheme: the action color as primary, Void/black background, the danger
 * fill as error. Not dynamic color: anything that carries meaning must not shift with the watch face. [mono] is the bundled
 * Cascadia Mono (`FontFamily(Font(R.font.cascadia_mono_regular))`); readouts and labels use it, everything else Roboto.
 */
@Composable
fun FusionSpaceWearTheme(mono: FontFamily = FontFamily.Monospace, content: @Composable () -> Unit) {
    val c = FsWearColors
    MaterialTheme(
        colorScheme = ColorScheme(
            primary = c.action, onPrimary = c.onAction, background = Color.Black, onBackground = c.ink,
            onSurface = c.ink, onSurfaceVariant = c.inkMuted, outline = c.ruleStrong, outlineVariant = c.rule,
            error = c.dangerFill, onError = c.onDangerFill,
        ),
    ) { FsWearMono.family = mono; content() }
}

internal object FsWearMono { var family: FontFamily = FontFamily.Monospace }
private fun label() = TextStyle(fontFamily = FsWearMono.family, fontSize = 11.sp, letterSpacing = 0.06.em, color = FsWearColors.inkMuted)
private fun readout(size: Int) = TextStyle(fontFamily = FsWearMono.family, fontSize = size.sp, fontFeatureSettings = "tnum, zero")

// ------------------------------------------------------------------ the way to the rocket

/** A Von Kármán nose cone pointing at the rocket relative to the wrist, on a ring with the heading at the top. Outline in ambient. */
@Composable
fun FsBearingArrow(relativeDegrees: Float, modifier: Modifier = Modifier, outline: Boolean = false) {
    val c = FsWearColors
    Canvas(modifier.clearAndSetSemantics {}) {
        val r = size.minDimension / 2 - 4.dp.toPx(); val ctr = center
        drawCircle(c.ruleStrong, r, ctr, style = Stroke(1.5.dp.toPx()))
        for (a in 0 until 360 step 30) {
            val t = a * PI.toFloat() / 180; val r0 = r - (if (a == 0) 7 else 4).dp.toPx()
            drawLine(c.inkMuted, Offset(ctr.x + r0 * sin(t), ctr.y - r0 * cos(t)), Offset(ctr.x + r * sin(t), ctr.y - r * cos(t)),
                strokeWidth = (if (a == 0) 2 else 1).dp.toPx())
        }
        rotate(relativeDegrees, ctr) {
            val tip = Offset(ctr.x, ctr.y - r + 10.dp.toPx()); val len = r * 0.78f; val rad = r * 0.3f
            val pts = (0..20).map { i ->
                val x = len * i / 20f; val th = acos(1 - 2 * x / len)
                x to (rad / sqrt(PI.toFloat()) * sqrt(th - sin(2 * th) / 2))
            }
            val cone = Path().apply {
                moveTo(tip.x - pts.last().second, tip.y + len)
                pts.reversed().forEach { (x, y) -> lineTo(tip.x - y, tip.y + x) }
                pts.forEach { (x, y) -> lineTo(tip.x + y, tip.y + x) }
                close()
            }
            if (outline) drawPath(cone, c.ink, style = Stroke(2.dp.toPx())) else drawPath(cone, c.ink)
            drawLine(c.ink, Offset(ctr.x, tip.y + len), Offset(ctr.x, ctr.y + r * 0.45f), strokeWidth = (if (outline) 2 else 4).dp.toPx())
        }
    }
}

/**
 * Find: the way to a landed rocket, how far, the bearing in degrees true and the fix's age, with "Found it" on the edge
 * button. In ambient mode it drops to outlines and muted ink, and says when it was true instead of how old it is.
 * [headingTrue] is null without a compass: the arrow then points from north, and the text says so.
 */
@Composable
fun FsWearFind(distanceFt: Int, bearingTrue: Float, headingTrue: Float?, fixAge: String, asOf: String, onFound: () -> Unit) {
    val ambient = LocalAmbientModeManager.current?.currentAmbientMode is AmbientMode.Ambient
    val c = FsWearColors
    val state = rememberTransformingLazyColumnState()
    AppScaffold(timeText = { TimeText() }) {
        ScreenScaffold(scrollState = state, edgeButton = {
            if (!ambient) EdgeButton(onClick = onFound, buttonSize = EdgeButtonSize.Medium) { Text("Found it") }
        }) { padding ->
            TransformingLazyColumn(state = state, contentPadding = padding) {
                item {
                    Column(
                        Modifier.fillMaxWidth().clearAndSetSemantics {
                            contentDescription = "Rocket $distanceFt feet away, bearing ${bearingTrue.toInt()} degrees true, fix $fixAge"
                        },
                        horizontalAlignment = Alignment.CenterHorizontally,
                    ) {
                        FsBearingArrow(bearingTrue - (headingTrue ?: 0f), Modifier.size(84.dp), outline = ambient)
                        Row(verticalAlignment = Alignment.Bottom, horizontalArrangement = Arrangement.spacedBy(4.dp)) {
                            Text("%,d".format(distanceFt), style = readout(28), color = if (ambient) c.inkMuted else c.ink)
                            Text("ft", style = label(), modifier = Modifier.padding(bottom = 5.dp))
                        }
                        val bearing = "%03d° T".format(bearingTrue.toInt() % 360)
                        Text(if (ambient) "$bearing · as of $asOf" else "$bearing · fix $fixAge" + if (headingTrue == null) " · from north" else "",
                            style = label().copy(letterSpacing = 0.em), textAlign = TextAlign.Center)
                    }
                }
            }
        }
    }
}

// ------------------------------------------------------------------ state and alerts

/** The device's state at the pad, read only: SAFE outlined or ARMED inverted. Safing is the switch or the phone. */
@Composable
fun FsWearStateBox(armed: Boolean, modifier: Modifier = Modifier) {
    val c = FsWearColors
    Text(
        if (armed) "ARMED" else "SAFE", style = readout(20).copy(fontWeight = FontWeight.SemiBold),
        color = if (armed) c.onDangerFill else c.ink,
        modifier = modifier.background(if (armed) c.dangerFill else Color.Transparent)
            .border(3.dp, if (armed) c.dangerFill else c.ink).padding(horizontal = 10.dp, vertical = 5.dp),
    )
}

/** A configured charge that didn't fire: full screen in Flare, first, taps repeating until "OK". The device keeps beeping. */
@Composable
fun FsWearUnfired(channel: String, onAcknowledge: () -> Unit) {
    val c = FsWearColors
    val context = LocalContext.current
    LaunchedEffect(Unit) { FsWristEvent.Unfired.play(context) }
    val state = rememberTransformingLazyColumnState()
    AppScaffold(timeText = { TimeText() }, modifier = Modifier.background(c.dangerFill)) {
        ScreenScaffold(scrollState = state, edgeButton = {
            EdgeButton(onClick = onAcknowledge, buttonSize = EdgeButtonSize.Medium) { Text("OK") }
        }) { padding ->
            TransformingLazyColumn(state = state, contentPadding = padding, modifier = Modifier.background(c.dangerFill)) {
                item {
                    Column(horizontalAlignment = Alignment.CenterHorizontally, modifier = Modifier.fillMaxWidth(0.8f)
                        .clearAndSetSemantics { contentDescription = "Unfired charge, $channel. Approach as live. Disarm before handling." }) {
                        Text("UNFIRED", style = readout(22).copy(fontWeight = FontWeight.SemiBold), color = c.onDangerFill)
                        Text(channel, style = readout(16), color = c.onDangerFill)
                        Text("Approach as live. Disarm before handling.", color = c.onDangerFill, textAlign = TextAlign.Center, fontSize = 12.sp)
                    }
                }
            }
        }
    }
}

// ------------------------------------------------------------------ the wrist language

/** One tap pattern per meaning, mirroring the device's beep language (product/embedded.md#beeps). Nothing routine taps. */
enum class FsWristEvent(private val primitives: IntArray, private val fallback: Int) {
    Liftoff(intArrayOf(VibrationEffect.Composition.PRIMITIVE_QUICK_RISE), VibrationEffect.EFFECT_HEAVY_CLICK),
    MainOut(intArrayOf(VibrationEffect.Composition.PRIMITIVE_CLICK), VibrationEffect.EFFECT_CLICK),
    LandedAllFired(intArrayOf(VibrationEffect.Composition.PRIMITIVE_CLICK, VibrationEffect.Composition.PRIMITIVE_CLICK), VibrationEffect.EFFECT_DOUBLE_CLICK),
    Unfired(intArrayOf(VibrationEffect.Composition.PRIMITIVE_THUD, VibrationEffect.Composition.PRIMITIVE_THUD, VibrationEffect.Composition.PRIMITIVE_THUD), VibrationEffect.EFFECT_HEAVY_CLICK),
    LinkLost(intArrayOf(VibrationEffect.Composition.PRIMITIVE_LOW_TICK, VibrationEffect.Composition.PRIMITIVE_LOW_TICK), VibrationEffect.EFFECT_TICK),
    LinkBack(intArrayOf(VibrationEffect.Composition.PRIMITIVE_TICK), VibrationEffect.EFFECT_TICK),
    Arrived(intArrayOf(VibrationEffect.Composition.PRIMITIVE_SLOW_RISE, VibrationEffect.Composition.PRIMITIVE_CLICK), VibrationEffect.EFFECT_HEAVY_CLICK);

    fun play(context: Context) {
        val v = context.getSystemService(Vibrator::class.java) ?: return
        val effect = if (v.areAllPrimitivesSupported(*primitives)) {
            VibrationEffect.startComposition().apply {
                primitives.forEachIndexed { i, p -> addPrimitive(p, 1f, if (i == 0) 0 else {{GAP_MS}}) }
            }.compose()
        } else VibrationEffect.createPredefined(fallback)
        v.vibrate(effect)
    }
}

// ------------------------------------------------------------------ tracking that survives the screen turning off

/**
 * The ongoing activity for Find, for Wear OS 6 and earlier: it keeps the app one tap away on the watch face and in the
 * launcher while tracking runs. On Wear OS 7 post a Live Update instead (Google's recommendation): the phone's builder in
 * product/mobile/compose/FsLiveUpdate.kt, with ProgressStyle, since Wear doesn't show MetricStyle. Call from the foreground
 * service that keeps location and the link alive; the notification is the service's.
 */
fun fsTrackingOngoing(context: Context, notificationId: Int, notification: NotificationCompat.Builder, iconRes: Int, open: PendingIntent,
                      distanceFt: Int, bearingTrue: Int): OngoingActivity =
    OngoingActivity.Builder(context, notificationId, notification)
        .setStaticIcon(iconRes)
        .setTouchIntent(open)
        .setStatus(Status.Builder().addTemplate("%,d ft · %03d° T".format(distanceFt, bearingTrue)).build())
        .build()
