// SPDX-License-Identifier: Apache-2.0 · Copyright 2026 Neer Patel
// FusionSpace parts for Wear OS (Compose for Wear OS, Material 3). Generated by tools/build/kit_watch.py from
// source/product/watch/; edit there. Standalone: the colors are the dark roles, written in below from the same values as
// product/tokens/ (a Wear app doesn't carry the phone's Material 3, so it can't use FusionSpaceColors.kt).
//
// A watch finds, glances and taps the wrist (product/watch.md). It never commands hardware: nothing here sends ARM, SAFE,
// FIRE or a configuration change.
package co.fusionspace.design.wear

import android.app.PendingIntent
import android.content.Context
import android.os.VibrationEffect
import android.os.Vibrator
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.calculateEndPadding
import androidx.compose.foundation.layout.calculateStartPadding
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.graphics.drawscope.rotate
import androidx.compose.ui.platform.LocalConfiguration
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalDensity
import androidx.compose.ui.platform.LocalLayoutDirection
import androidx.compose.ui.semantics.clearAndSetSemantics
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.em
import androidx.compose.ui.unit.sp
import androidx.core.app.NotificationCompat
import androidx.wear.compose.foundation.AmbientMode
import androidx.wear.compose.foundation.LocalAmbientModeManager
import androidx.wear.compose.foundation.lazy.TransformingLazyColumn
import androidx.wear.compose.foundation.lazy.rememberTransformingLazyColumnState
import androidx.wear.compose.foundation.rememberAmbientModeManager
import androidx.wear.compose.material3.AppScaffold
import androidx.wear.compose.material3.ButtonDefaults
import androidx.wear.compose.material3.ColorScheme
import androidx.wear.compose.material3.EdgeButton
import androidx.wear.compose.material3.EdgeButtonSize
import androidx.wear.compose.material3.MaterialTheme
import androidx.wear.compose.material3.ScreenScaffold
import androidx.wear.compose.material3.Text
import androidx.wear.compose.material3.TimeText
import androidx.wear.ongoing.OngoingActivity
import androidx.wear.ongoing.Status
import kotlin.math.PI
import kotlin.math.acos
import kotlin.math.cos
import kotlin.math.sin
import kotlin.math.sqrt

// ------------------------------------------------------------------ colors and theme

/** The dark roles and signal fills (product/foundations.md). A watch is an emissive screen: always dark. */
object FsWearColors {
    val canvas = Color(0xFF0B0F1C)   // Page and screen background
    val surface = Color(0xFF141A2B)   // Raised panels, inputs, tables, dialogs (separated by rules, never shadows)
    val rule = Color(0xFF2A3248)   // Hairlines between rows, sections and cells (decoration: no contrast minimum)
    val ruleStrong = Color(0xFF6D7790)   // Control borders and chart axes (3:1 against canvas and surface)
    val ink = Color(0xFFF3F4F7)   // Text, primary lines, measured data
    val inkMuted = Color(0xFF98A1B8)   // Secondary text: labels, units, captions, sources
    val inkFaint = Color(0xFF566079)   // Disabled text and hatching (not for anything that must be read, placeholders included)
    val action = Color(0xFF768DF5)   // Links, selection, focus, the one interactive accent
    val onAction = Color(0xFF0B0F1C)   // Text on an action fill
    val focus = Color(0xFF768DF5)   // Focus ring (2 px outline, 2 px offset)
    val danger = Color(0xFFFB8083)   // Danger ink: text, icons and lines
    val caution = Color(0xFFF5AF20)   // Caution ink: text, icons and lines
    val ok = Color(0xFF6AD5B6)   // Normal ink: text, icons and lines
    val predicted = Color(0xFFED89D2)   // Predicted, simulated or forecast data (always dashed or hatched too)
    val dangerFill = Color(0xFFAC001E)
    val onDangerFill = Color(0xFFFFFFFF)
    val cautionFill = Color(0xFFF5AF20)
    val onCautionFill = Color(0xFF0B0F1C)
    val okFill = Color(0xFF0A6355)
    val onOkFill = Color(0xFFFFFFFF)
    val infoFill = Color(0xFF3350D6)
    val onInfoFill = Color(0xFFFFFFFF)
}

/**
 * Material 3 for Wear OS with the static FusionSpace scheme: the action color as primary, Void/black background, the danger
 * fill as error. Not dynamic color: anything that carries meaning must not shift with the watch face. [mono] is the bundled
 * Cascadia Mono (`FontFamily(Font(R.font.cascadia_mono_regular))`); readouts and labels use it, everything else Roboto.
 * It also provides LocalAmbientModeManager when the app hasn't (its default is null, which would keep every screen
 * here out of ambient mode for good).
 */
@Composable
fun FusionSpaceWearTheme(mono: FontFamily = FontFamily.Monospace, content: @Composable () -> Unit) {
    val c = FsWearColors
    MaterialTheme(
        colorScheme = ColorScheme(
            primary = c.action, onPrimary = c.onAction, background = Color.Black, onBackground = c.ink,
            onSurface = c.ink, onSurfaceVariant = c.inkMuted, outline = c.ruleStrong, outlineVariant = c.rule,
            error = c.dangerFill, onError = c.onDangerFill,
        ),
    ) {
        FsWearMono.family = mono
        if (LocalAmbientModeManager.current != null) content()
        else CompositionLocalProvider(LocalAmbientModeManager provides rememberAmbientModeManager(), content = content)
    }
}

/**
 * ScreenScaffold's padding for a list, with the top grown by as much as the time above it grows with the text size (the
 * scaffold's top padding stays the same at every size, so at the largest sizes the first item would run into the time).
 */
@Composable
fun fsClearOfTime(padding: PaddingValues): PaddingValues {
    val dir = LocalLayoutDirection.current
    val grow = ((LocalDensity.current.fontScale - 1f).coerceAtLeast(0f) * 32).dp
    return PaddingValues(start = padding.calculateStartPadding(dir), end = padding.calculateEndPadding(dir),
        top = padding.calculateTopPadding() + grow, bottom = padding.calculateBottomPadding())
}

internal object FsWearMono { var family: FontFamily = FontFamily.Monospace }
private fun label() = TextStyle(fontFamily = FsWearMono.family, fontSize = 11.sp, letterSpacing = 0.06.em, color = FsWearColors.inkMuted)
private fun readout(size: Int) = TextStyle(fontFamily = FsWearMono.family, fontSize = size.sp, fontFeatureSettings = "tnum, zero")

// ------------------------------------------------------------------ the way to the rocket

/** A Von Kármán nose cone pointing at the rocket relative to the wrist, on a ring with the heading at the top. Outline in ambient. */
@Composable
fun FsBearingArrow(relativeDegrees: Float, modifier: Modifier = Modifier, outline: Boolean = false) {
    val c = FsWearColors
    Canvas(modifier.clearAndSetSemantics {}) {
        val r = size.minDimension / 2 - 4.dp.toPx(); val ctr = center
        drawCircle(c.ruleStrong, r, ctr, style = Stroke(1.5.dp.toPx()))
        for (a in 0 until 360 step 30) {
            val t = a * PI.toFloat() / 180; val r0 = r - (if (a == 0) 7 else 4).dp.toPx()
            drawLine(c.inkMuted, Offset(ctr.x + r0 * sin(t), ctr.y - r0 * cos(t)), Offset(ctr.x + r * sin(t), ctr.y - r * cos(t)),
                strokeWidth = (if (a == 0) 2 else 1).dp.toPx())
        }
        rotate(relativeDegrees, ctr) {
            val tip = Offset(ctr.x, ctr.y - r + 10.dp.toPx()); val len = r * 0.78f; val rad = r * 0.3f
            val pts = (0..20).map { i ->
                val x = len * i / 20f; val th = acos(1 - 2 * x / len)
                x to (rad / sqrt(PI.toFloat()) * sqrt(th - sin(2 * th) / 2))
            }
            val cone = Path().apply {
                moveTo(tip.x - pts.last().second, tip.y + len)
                pts.reversed().forEach { (x, y) -> lineTo(tip.x - y, tip.y + x) }
                pts.forEach { (x, y) -> lineTo(tip.x + y, tip.y + x) }
                close()
            }
            if (outline) drawPath(cone, c.ink, style = Stroke(2.dp.toPx())) else drawPath(cone, c.ink)
            drawLine(c.ink, Offset(ctr.x, tip.y + len), Offset(ctr.x, ctr.y + r * 0.45f), strokeWidth = (if (outline) 2 else 4).dp.toPx())
        }
    }
}

/**
 * Find: the way to a landed rocket, how far, the bearing in degrees true and the fix's age, with "Found it" on the edge
 * button. In ambient mode it drops to outlines and muted ink, and says when it was true instead of how old it is.
 * [headingTrue] is null without a compass: the arrow then points from north, and the text says so.
 */
@Composable
fun FsWearFind(distanceFt: Int, bearingTrue: Float, headingTrue: Float?, fixAge: String, asOf: String, onFound: () -> Unit) {
    val ambient = LocalAmbientModeManager.current?.currentAmbientMode is AmbientMode.Ambient
    val c = FsWearColors
    // Wear OS's small class (192-224 dp) gets a smaller arrow and readout, so the edge button keeps its whole label.
    val small = LocalConfiguration.current.screenWidthDp < 225
    val state = rememberTransformingLazyColumnState()
    AppScaffold(timeText = { TimeText() }) {
        ScreenScaffold(scrollState = state, edgeButton = {
            // In ambient the control stays, shown as unavailable: outlined and muted, no fill (product/watch.md#always-on-and-ambient).
            EdgeButton(
                onClick = onFound, buttonSize = EdgeButtonSize.Medium, enabled = !ambient,
                colors = if (ambient) ButtonDefaults.outlinedButtonColors(contentColor = c.inkMuted, disabledContentColor = c.inkMuted)
                else ButtonDefaults.buttonColors(),
                border = if (ambient) BorderStroke(1.dp, c.ruleStrong) else null,
            ) { Text("Found it") }
        }) { padding ->
            TransformingLazyColumn(state = state, contentPadding = fsClearOfTime(padding)) {
                item {
                    Column(
                        Modifier.fillMaxWidth().clearAndSetSemantics {
                            contentDescription = "Rocket $distanceFt feet away, bearing ${bearingTrue.toInt()} degrees true, fix $fixAge"
                        },
                        horizontalAlignment = Alignment.CenterHorizontally,
                    ) {
                        FsBearingArrow(bearingTrue - (headingTrue ?: 0f), Modifier.size(if (small) 56.dp else 84.dp), outline = ambient)
                        Row(verticalAlignment = Alignment.Bottom, horizontalArrangement = Arrangement.spacedBy(4.dp)) {
                            Text("%,d".format(distanceFt), style = readout(if (small) 24 else 28), color = if (ambient) c.inkMuted else c.ink)
                            Text("ft", style = label(), modifier = Modifier.padding(bottom = 5.dp))
                        }
                        val bearing = "%03d°\u00A0T".format(bearingTrue.toInt() % 360)
                        Text(if (ambient) "$bearing · as of $asOf" else "$bearing · fix $fixAge" + if (headingTrue == null) " · from north" else "",
                            style = label().copy(letterSpacing = 0.em), textAlign = TextAlign.Center)
                    }
                }
            }
        }
    }
}

// ------------------------------------------------------------------ state and alerts

/**
 * The device's state at the pad, read only: SAFE outlined or ARMED inverted. Safing is the switch or the phone. In ambient
 * the fill becomes an outline (ARMED stays a word in its box, in danger ink) and SAFE turns muted.
 */
@Composable
fun FsWearStateBox(armed: Boolean, modifier: Modifier = Modifier) {
    val c = FsWearColors
    val ambient = LocalAmbientModeManager.current?.currentAmbientMode is AmbientMode.Ambient
    val ink = when { ambient && armed -> c.danger; ambient -> c.inkMuted; armed -> c.onDangerFill; else -> c.ink }
    val word = if (armed) "ARMED" else "SAFE"
    Text(
        word, style = readout(20).copy(fontWeight = FontWeight.SemiBold), color = ink,
        modifier = modifier.clearAndSetSemantics { contentDescription = "Device state: $word" }.background(if (armed && !ambient) c.dangerFill else Color.Transparent)
            .border(3.dp, if (armed && !ambient) c.dangerFill else ink).padding(horizontal = 10.dp, vertical = 5.dp),
    )
}

/**
 * A configured charge that didn't fire: full screen in Flare, first, taps repeating until "OK". The device keeps beeping.
 * In ambient the Flare fill would break the burn-in rules (85% black, no fills), so the screen turns black and UNFIRED
 * stays as a word in its box, in danger ink.
 */
@Composable
fun FsWearUnfired(channel: String, onAcknowledge: () -> Unit) {
    val c = FsWearColors
    val context = LocalContext.current
    val ambient = LocalAmbientModeManager.current?.currentAmbientMode is AmbientMode.Ambient
    val bg = if (ambient) Color.Black else c.dangerFill
    val fg = if (ambient) c.danger else c.onDangerFill
    LaunchedEffect(Unit) { FsWristEvent.Unfired.play(context) }
    val state = rememberTransformingLazyColumnState()
    AppScaffold(timeText = { TimeText() }, modifier = Modifier.background(bg)) {
        ScreenScaffold(scrollState = state, edgeButton = {
            // OK in the inverse of the screen (Paper on Flare), not the action color, which would clash with the Flare fill.
            EdgeButton(
                onClick = onAcknowledge, buttonSize = EdgeButtonSize.Medium, enabled = !ambient,
                colors = if (ambient) ButtonDefaults.outlinedButtonColors(contentColor = c.inkMuted, disabledContentColor = c.inkMuted)
                else ButtonDefaults.buttonColors(containerColor = c.onDangerFill, contentColor = c.dangerFill),
                border = if (ambient) BorderStroke(1.dp, c.ruleStrong) else null,
            ) { Text("OK") }
        }) { padding ->
            TransformingLazyColumn(state = state, contentPadding = fsClearOfTime(padding), modifier = Modifier.background(bg)) {
                item {
                    Column(horizontalAlignment = Alignment.CenterHorizontally, verticalArrangement = Arrangement.spacedBy(2.dp),
                        modifier = Modifier.fillMaxWidth().padding(horizontal = 24.dp)
                            .clearAndSetSemantics { contentDescription = "Unfired charge, $channel. Approach as live. Disarm before handling." }) {
                        Text("UNFIRED", style = readout(22).copy(fontWeight = FontWeight.SemiBold), color = fg,
                            modifier = if (ambient) Modifier.border(2.dp, c.danger).padding(horizontal = 8.dp, vertical = 2.dp) else Modifier)
                        Text(channel, style = readout(16), color = fg)
                        Text("Approach as live. Disarm before handling.", color = fg, textAlign = TextAlign.Center, fontSize = 12.sp)
                    }
                }
            }
        }
    }
}

// ------------------------------------------------------------------ the wrist language

/** One tap pattern per meaning, mirroring the device's beep language (product/embedded.md#beeps). Nothing routine taps. */
enum class FsWristEvent(private val primitives: IntArray, private val fallback: Int) {
    Liftoff(intArrayOf(VibrationEffect.Composition.PRIMITIVE_QUICK_RISE), VibrationEffect.EFFECT_HEAVY_CLICK),
    MainOut(intArrayOf(VibrationEffect.Composition.PRIMITIVE_CLICK), VibrationEffect.EFFECT_CLICK),
    LandedAllFired(intArrayOf(VibrationEffect.Composition.PRIMITIVE_CLICK, VibrationEffect.Composition.PRIMITIVE_CLICK), VibrationEffect.EFFECT_DOUBLE_CLICK),
    Unfired(intArrayOf(VibrationEffect.Composition.PRIMITIVE_THUD, VibrationEffect.Composition.PRIMITIVE_THUD, VibrationEffect.Composition.PRIMITIVE_THUD), VibrationEffect.EFFECT_HEAVY_CLICK),
    LinkLost(intArrayOf(VibrationEffect.Composition.PRIMITIVE_LOW_TICK, VibrationEffect.Composition.PRIMITIVE_LOW_TICK), VibrationEffect.EFFECT_TICK),
    LinkBack(intArrayOf(VibrationEffect.Composition.PRIMITIVE_TICK), VibrationEffect.EFFECT_TICK),
    Arrived(intArrayOf(VibrationEffect.Composition.PRIMITIVE_SLOW_RISE, VibrationEffect.Composition.PRIMITIVE_CLICK), VibrationEffect.EFFECT_HEAVY_CLICK);

    fun play(context: Context) {
        val v = context.getSystemService(Vibrator::class.java) ?: return
        val effect = if (v.areAllPrimitivesSupported(*primitives)) {
            VibrationEffect.startComposition().apply {
                primitives.forEachIndexed { i, p -> addPrimitive(p, 1f, if (i == 0) 0 else 600) }
            }.compose()
        } else VibrationEffect.createPredefined(fallback)
        v.vibrate(effect)
    }
}

// ------------------------------------------------------------------ tracking that survives the screen turning off

/**
 * The ongoing activity for Find, for Wear OS 6 and earlier: it keeps the app one tap away on the watch face and in the
 * launcher while tracking runs. On Wear OS 7 post a Live Update instead (Google's recommendation): the phone's builder in
 * product/mobile/compose/FsLiveUpdate.kt, with ProgressStyle, since Wear doesn't show MetricStyle. Call from the foreground
 * service that keeps location and the link alive; the notification is the service's.
 */
fun fsTrackingOngoing(context: Context, notificationId: Int, notification: NotificationCompat.Builder, iconRes: Int, open: PendingIntent,
                      distanceFt: Int, bearingTrue: Int): OngoingActivity =
    OngoingActivity.Builder(context, notificationId, notification)
        .setStaticIcon(iconRes)
        .setTouchIntent(open)
        .setStatus(Status.Builder().addTemplate("%,d\u00A0ft · %03d°\u00A0T".format(distanceFt, bearingTrue)).build())
        .build()
