// SPDX-License-Identifier: Apache-2.0 · Copyright 2026 Neer Patel
// A FusionSpace widget, worked through: Window's surface wind (product/mobile/glance/ios-widgets.png). Generated by
// tools/build/kit_mobile.py from source/product/mobile/; edit there. Needs FusionSpaceColors.swift. iOS 17+, macOS 14+.
//
// The rules it shows (product/mobile.md#glanceable-surfaces): one readout with its unit and its age; meaning in words and
// shapes, so it still reads in tinted, clear and vibrant modes, where the system draws everything in one tint; the value is
// the accent group; no logo. Add it to your widget bundle: `FSWindWidget()`.
import SwiftUI
import WidgetKit

public struct FSWindEntry: TimelineEntry, Sendable {
    public let date: Date            // when the timeline shows this entry
    public let measuredAt: Date      // when the station measured it: the age shown comes from this, not from `date`
    public let windMph: Int, gustMph: Int?, fromDegrees: Int
    public let limitMph: Int         // the NAR and Tripoli surface-wind limit, 20 mph

    public var nearLimit: Bool { (gustMph ?? windMph) >= limitMph - 2 }
    public var overLimit: Bool { (gustMph ?? windMph) > limitMph }

    public static let example = FSWindEntry(date: .now, measuredAt: .now.addingTimeInterval(-240), windMph: 12, gustMph: 19,
                                            fromDegrees: 270, limitMph: 20)
}

public struct FSWindProvider: TimelineProvider {
    public init() {}
    public func placeholder(in context: Context) -> FSWindEntry { .example }
    public func getSnapshot(in context: Context, completion: @escaping (FSWindEntry) -> Void) { completion(.example) }
    public func getTimeline(in context: Context, completion: @escaping (Timeline<FSWindEntry>) -> Void) {
        // Read the last observation the app saved (the widget never fetches at the field). Refresh every 15 minutes; past
        // 30 minutes the view shows the value as stale instead of pretending it's current.
        let e = FSWindEntry.example
        let entries = (0..<4).map { i in
            FSWindEntry(date: .now.addingTimeInterval(Double(i) * 900), measuredAt: e.measuredAt, windMph: e.windMph,
                        gustMph: e.gustMph, fromDegrees: e.fromDegrees, limitMph: e.limitMph)
        }
        completion(Timeline(entries: entries, policy: .after(.now.addingTimeInterval(3600))))
    }
}

struct FSWindView: View {
    let entry: FSWindEntry
    @Environment(\.widgetFamily) private var family
    @Environment(\.widgetRenderingMode) private var mode
    @Environment(\.colorScheme) private var scheme

    private var p: FSPalette { scheme == .dark ? FS.darkPalette : FS.lightPalette }
    private var stale: Bool { FSFreshness.isStale(since: entry.measuredAt, limit: FSFreshness.weather, now: entry.date) }
    private var age: String { FSFreshness.age(since: entry.measuredAt, now: entry.date) }

    var body: some View {
        switch family {
        #if os(iOS)
        case .accessoryRectangular: rectangular
        case .accessoryInline: Text("Wind \(entry.windMph) mph\(gust) · \(age)")
        #endif
        case .systemMedium: HStack(alignment: .top, spacing: 12) { main; Spacer(minLength: 0) }
        default: main
        }
    }

    private var gust: String { entry.gustMph.map { " G\($0)" } ?? "" }

    private var main: some View {
        VStack(alignment: .leading, spacing: 4) {
            Text("SURFACE WIND").font(FS.label()).tracking(0.7).foregroundStyle(p.inkMuted)
            HStack(alignment: .firstTextBaseline, spacing: 6) {
                Text("\(entry.windMph)").font(FS.readout(34, relativeTo: .largeTitle))
                    .foregroundStyle(stale ? p.inkMuted : p.ink)
                    .widgetAccentable()
                Text("mph").font(FS.label()).foregroundStyle(p.inkMuted)
            }
            if let g = entry.gustMph {
                Text("Gusts \(g) · from \(entry.fromDegrees)°").font(.footnote).foregroundStyle(p.inkMuted)
            }
            if entry.nearLimit { limitTag }
            Spacer(minLength: 0)
            Text(stale ? "Stale · \(age)" : age).font(.caption2).foregroundStyle(p.inkMuted)
        }
        .accessibilityElement(children: .combine)
    }

    /// Caution as a word and a triangle. Full color: a Sodium fill. Accented and vibrant: an outline in the system's tint.
    private var limitTag: some View {
        let word = entry.overLimit ? "OVER LIMIT" : "NEAR LIMIT"
        let full = mode == .fullColor
        return Label(word, systemImage: "exclamationmark.triangle")
            .font(FS.labelStrong())
            .padding(.horizontal, 6).padding(.vertical, 2)
            .foregroundStyle(full ? FS.onCautionFill : p.ink)
            .background(full ? FS.cautionFill : Color.clear)
            .overlay(Rectangle().strokeBorder(full ? Color.clear : p.ink, lineWidth: 1.5))
    }

    #if os(iOS)
    private var rectangular: some View {
        VStack(alignment: .leading, spacing: 0) {
            Text("WIND · \(age)").font(FS.label())
            Text("\(entry.windMph) mph\(gust)").font(FS.readout(20, relativeTo: .headline)).widgetAccentable()
            if entry.nearLimit { Label("near the \(entry.limitMph) mph limit", systemImage: "exclamationmark.triangle").font(.caption2) }
        }
    }
    #endif
}

public struct FSWindWidget: Widget {
    public init() {}
    public var body: some WidgetConfiguration {
        StaticConfiguration(kind: "co.fusionspace.window.wind", provider: FSWindProvider()) { entry in
            FSWindView(entry: entry)
                .containerBackground(for: .widget) { FSWidgetBackground() }
        }
        .configurationDisplayName("Surface wind")
        .description("Wind at your field, with its age and how close it is to the limit.")
        .supportedFamilies(families)
    }
    private var families: [WidgetFamily] {
        #if os(iOS)
        return [.systemSmall, .systemMedium, .accessoryRectangular, .accessoryInline]
        #else
        return [.systemSmall, .systemMedium]
        #endif
    }
}

/// The surface role. The system removes it in accented and vibrant modes.
struct FSWidgetBackground: View {
    @Environment(\.colorScheme) private var scheme
    var body: some View { (scheme == .dark ? FS.darkPalette : FS.lightPalette).surface }
}
